### ISSUE TITLE
S12 Pro

### ISSUE THREAD

**Issue by ktauchathuranga** [openwrt/asu#1096]
Request Data:

{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r23124-49aaab08ea",
    "advanced_mode": "0",
    "sha256_unsigned": "",
    "branch": "23.05",
    "efi": null,
    "profile": "tozed,zlt-s12-pro",
    "target": "ramips/mt7621",
    "version": "23.05-SNAPSHOT",
    "packages": [
        "adb",
        "attendedsysupgrade-common",
        "banip",
        "base-files",
        "bcp38",
        "busybox",
        "ca-bundle",
        "cgi-io",
        "chat",
        "comgt",
        "comgt-ncm",
        "dnsmasq",
        "dropbear",
        "firewall4",
        "fstools",
        "fwtool",
        "getrandom",
        "hostapd-common",
        "ip-tiny",
        "ip6tables-nft",
        "ipset",
        "iptables-mod-conntrack-extra",
        "iptables-mod-ipopt",
        "iptables-nft",
        "iw",
        "iwinfo",
        "jansson",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-cfg80211",
        "kmod-crypto-acompress",
        "kmod-crypto-aead",
        "kmod-crypto-ccm",
        "kmod-crypto-cmac",
        "kmod-crypto-crc32c",
        "kmod-crypto-ctr",
        "kmod-crypto-gcm",
        "kmod-crypto-gf128",
        "kmod-crypto-ghash",
        "kmod-crypto-hash",
        "kmod-crypto-hmac",
        "kmod-crypto-lib-chacha20",
        "kmod-crypto-lib-chacha20poly1305",
        "kmod-crypto-lib-curve25519",
        "kmod-crypto-lib-poly1305",
        "kmod-crypto-manager",
        "kmod-crypto-null",
        "kmod-crypto-rng",
        "kmod-crypto-seqiv",
        "kmod-crypto-sha512",
        "kmod-gpio-button-hotplug",
        "kmod-ifb",
        "kmod-ip6tables",
        "kmod-ipt-conntrack",
        "kmod-ipt-conntrack-extra",
        "kmod-ipt-core",
        "kmod-ipt-ipopt",
        "kmod-ipt-ipset",
        "kmod-leds-gpio",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc32c",
        "kmod-lib-lzo",
        "kmod-mac80211",
        "kmod-mii",
        "kmod-mt76-core",
        "kmod-mt7603",
        "kmod-mt76x02-common",
        "kmod-mt76x2",
        "kmod-mt76x2-common",
        "kmod-nf-conncount",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack-netlink",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-ipt",
        "kmod-nf-ipt6",
        "kmod-nf-log",
        "kmod-nf-log6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nfnetlink",
        "kmod-nft-compat",
        "kmod-nft-core",
        "kmod-nft-fib",
        "kmod-nft-nat",
        "kmod-nft-offload",
        "kmod-nls-base",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-sched-cake",
        "kmod-sched-core",
        "kmod-slhc",
        "kmod-udptunnel4",
        "kmod-udptunnel6",
        "kmod-usb-core",
        "kmod-usb-net",
        "kmod-usb-net-cdc-ether",
        "kmod-usb-net-cdc-mbim",
        "kmod-usb-net-cdc-ncm",
        "kmod-usb-net-huawei-cdc-ncm",
        "kmod-usb-net-qmi-wwan",
        "kmod-usb-serial",
        "kmod-usb-serial-option",
        "kmod-usb-serial-wwan",
        "kmod-usb-wdm",
        "kmod-usb-xhci-hcd",
        "kmod-usb-xhci-mtk",
        "kmod-usb3",
        "kmod-wireguard",
        "libblobmsg-json",
        "libevdev",
        "libevent2",
        "libgcrypt",
        "libgpg-error",
        "libipset",
        "libiptext",
        "libiptext-nft",
        "libiptext6",
        "libiwinfo",
        "libiwinfo-data",
        "libjson-c",
        "libjson-script",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "liblucihttp-ucode",
        "libmnl",
        "libnftnl",
        "libnl-tiny",
        "libopenssl",
        "libopenssl-conf",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuclient",
        "libucode",
        "libudev-zero",
        "libunbound",
        "libusb-1.0",
        "libustream-openssl",
        "libxtables",
        "logd",
        "lua",
        "luci-app-3ginfo-lite",
        "luci-app-attendedsysupgrade",
        "luci-app-banip",
        "luci-app-bcp38",
        "luci-app-commands",
        "luci-app-firewall",
        "luci-app-mwan3",
        "luci-app-nlbwmon",
        "luci-app-openvpn",
        "luci-app-opkg",
        "luci-app-sqm",
        "luci-app-unbound",
        "luci-app-wifischedule",
        "luci-base",
        "luci-compat",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-json",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-light",
        "luci-lua-runtime",
        "luci-mod-admin-full",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-proto-ipv6",
        "luci-proto-ncm",
        "luci-proto-ppp",
        "luci-proto-wireguard",
        "luci-ssl-openssl",
        "luci-theme-bootstrap",
        "modemband",
        "mtd",
        "mwan3",
        "netifd",
        "nftables-json",
        "nlbwmon",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openssl-util",
        "openwrt-keyring",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-iwinfo",
        "rpcd-mod-luci",
        "rpcd-mod-rpcsys",
        "rpcd-mod-rrdns",
        "rpcd-mod-ucode",
        "rssileds",
        "s12-pro-signald",
        "sms-tool",
        "sqm-scripts",
        "tc-tiny",
        "ubi-utils",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "ucode",
        "ucode-mod-fs",
        "ucode-mod-html",
        "ucode-mod-lua",
        "ucode-mod-math",
        "ucode-mod-ubus",
        "ucode-mod-uci",
        "uhttpd",
        "uhttpd-mod-ubus",
        "umbim",
        "umdns",
        "unbound-daemon",
        "uqmi",
        "urandom-seed",
        "urngd",
        "usbids",
        "usbutils",
        "usign",
        "usteer",
        "wifischedule",
        "wireguard-tools",
        "wireless-regdb",
        "wpad-openssl",
        "wwan",
        "xtables-nft",
        "zlib"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-23.132.65998-fa9fb2f"
}
STDERR:
Generate local signing keys...
Generate local certificate...
Package list missing or not up-to-date, generating it.

Building package index...
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/targets/ramips/mt7621/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-mipsel_24kc_musl/root-ramips/../../../../builder/dl/openwrt_core
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/targets/ramips/mt7621/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/base/Packages.gz
Updated list of available packages in /builder/build_dir/target-mipsel_24kc_musl/root-ramips/../../../../builder/dl/openwrt_base
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/targets/ramips/mt7621/kmods/5.15.173-1-a06e4ddf7c2c8989cf7a04710ef4c0de/Packages.gz
Updated list of available packages in /builder/build_dir/target-mipsel_24kc_musl/root-ramips/../../../../builder/dl/openwrt_kmods
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/targets/ramips/mt7621/kmods/5.15.173-1-a06e4ddf7c2c8989cf7a04710ef4c0de/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/luci/Packages.gz
Updated list of available packages in /builder/build_dir/target-mipsel_24kc_musl/root-ramips/../../../../builder/dl/openwrt_luci
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-mipsel_24kc_musl/root-ramips/../../../../builder/dl/openwrt_packages
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/routing/Packages.gz
Updated list of available packages in /builder/build_dir/target-mipsel_24kc_musl/root-ramips/../../../../builder/dl/openwrt_routing
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/telephony/Packages.gz
Updated list of available packages in /builder/build_dir/target-mipsel_24kc_musl/root-ramips/../../../../builder/dl/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/23.05-SNAPSHOT/packages/mipsel_24kc/telephony/Packages.sig
Signature check passed.
Downloading file:packages/Packages
Updated list of available packages in /builder/build_dir/target-mipsel_24kc_musl/root-ramips/../../../../builder/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check passed.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-app-3ginfo-lite.
 * opkg_install_cmd: Cannot install package modemband.
 * opkg_install_cmd: Cannot install package s12-pro-signald.
make[2]: *** [Makefile:189: package_install] Error 255
make[1]: *** [Makefile:154: _call_manifest] Error 2
make: *** [Makefile:274: manifest] Error 2

**Comment by efahl** [comment]
Those three packages don't appear to be in any of the official OpenWrt repos.  Are you running a vendor-specific variant?

**Comment by ktauchathuranga** [comment]
thank you for the reply,
i tried so many things, and at one point it fixed,
now i dont remember exactly what caused that.
but however, the problem is fixed for me.
and i am sorry i cant exactly tell to the community how it was fixed. 👻
