### ISSUE TITLE
Server Stats page should include the Start Date for accumulating stats

### ISSUE THREAD

**Issue by richb-hanover** [openwrt/asu#307]
It would be good to include the "start time" on the Serve Stats page. That is, asu.aparcar.org now shows 1,364 builds for SNAPSHOT. But since when? 

Knowing the date gives a little context to these stats. We can do the mental arithmetic to say X builds/day (week/month/etc) for this target.

Here's a SWAG (Scientific Wild Ass Guess); I have been keeping records for the last couple days. That count was 1,307 at 1330 on 10 Oct, so that's about 57 builds in 42 hours, or about 33 builds/day. So I'm guessing that the stats started at zero on that server around 40 days ago, or sometime in early September...

Am I close? Thanks.

**Comment by aparcar** [comment]
I think the best would be to have ASU export monitoring data in the Prometheus data format and let Prometheus do the aggregation etc. It doesn't make a lot of sense to me building our own monitoring interface etc. The `/stats/` overview is fine to monitor things over time something else should be used.

**Comment by richb-hanover** [comment]
OK. I don't feel strongly about this: more curiosity than anything else. I will close it. Thanks.

**Comment by aparcar** [comment]
I created a dashboard to show some stats, I'll extend it and make it public soonish.

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/16000931/158155995-b7cf5447-1c8c-47cb-a929-f5541901d851.png">

**Comment by richb-hanover** [comment]
Hey! This must be a REAL project if it has a sexy dashboard! :-) 

Looks great - thanks.

**Comment by aparcar** [comment]
Please have a look at https://asu.aparcar.org/stats/ and let me know what stats/graph seem useful for you!

**Comment by aparcar** [comment]
Now also at https://sysupgrade.openwrt.org/stats/

**Comment by richb-hanover** [comment]
WOW! This is so sexy!

I have a bunch of clarifying observations/questions. Is there an "About..." where we might be able to include some of this info?

* It's worth noting that the page summarizes build request received by the sysupgrade (or aparcar) image builder machine.
* The bar chart at the top shows which builds have been requested recently. I assume "Snapshot" is the master, and that "21.02-Snapshot" is the latest for the 21.02 branch
* Builds by Profile - this is the number of specific builds for particular devices that have been requested. Useful for finding popular devices.
* Builds by target - this is the target/architecture of the builds. How might this be useful?
* I have a question about how the charts work. For instance, on asu.aparcar.org, setting the Profile to a week, I see that all build counts started at zero a couple days ago, and click up. This makes sense.
* What happens a year from now? Let's say that the linksys_e8450-ubi was really popular and was top of the list with 5000 builds over the last year. But then (for some hypothetical reason) no one ever built it again, and the XYZ123 model started to be popular, with 100 builds per week. Would it takes months before the XYZ123 began to be prominent in the weekly stats? 

Thanks again for all the work you do.

**Comment by aparcar** [comment]
> It's worth noting that the page summarizes build request received by the sysupgrade (or aparcar) image builder machine.

Sure, it's just a fancy counter how many images where build. This could be "build in the last hour" or whatever.

> The bar chart at the top shows which builds have been requested recently. I assume "Snapshot" is the master, and that "21.02-Snapshot" is the latest for the 21.02 branch

Yes, that follows naming schema you have on downloads.openwrt.org/releases/

> Builds by Profile - this is the number of specific builds for particular devices that have been requested. Useful for finding popular devices.

This should become a monthly overview with the increase rate, not so much the overall builds.

> Builds by target - this is the target/architecture of the builds. How might this be useful?

Not sure at this point.

> I have a question about how the charts work. For instance, on asu.aparcar.org, setting the Profile to a week, I see that all build counts started at zero a couple days ago, and click up. This makes sense.

Those are all counters, they go up forever. What we can do with Grafana/Prometheus is measure the change of it.

> What happens a year from now? Let's say that the linksys_e8450-ubi was really popular and was top of the list with 5000 builds over the last year. But then (for some hypothetical reason) no one ever built it again, and the XYZ123 model started to be popular, with 100 builds per week. Would it takes months before the XYZ123 began to be prominent in the weekly stats?

Correct, we should make it show the "rate" and not the "total count"

**Comment by aparcar** [comment]
Okay I reworked the status view to have the top right dropdown determine what timespan you're looking at. It can be something like 7days or 30 minutes, all graphs show the "change" for that time. I also added cache hits and popular package installations. I think stats are fine for now, we may extend things later if more specific things come up.

**Comment by richb-hanover** [comment]
I think the stats are **better** than fine! This is awesome. Thanks!
