### ISSUE TITLE
pressing capital Y instead of small letter Y causes failure in auc

### ISSUE THREAD

**Issue by chuacw** [openwrt/asu#316]
pressing capital Y instead of small letter Y causes failure in auc

Please accept both capital and small letter Ys
![image](https://user-images.githubusercontent.com/1757930/151492166-ee7190ee-039c-4234-8eac-9c3b6bc53f51.png)

**Comment by aparcar** [comment]
Fixed via https://github.com/openwrt/packages/commit/d27ecdcc49f2d91a8758ff4c416385d6d57cf2e6
