### ISSUE TITLE
This works?

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/asu#317]
I followed the steps for Docker and I can't get the server.

**Comment by aparcar** [comment]
I recently worked on the docker-compose.yml file, please give this another try.

**Comment by aparcar** [comment]
Closing this due to no response, open again if the issue still exists.

**Comment by dangowrt** [comment]
Yes, this is the server software running at asu.aparcar.org and sysupgrade.openwrt.org. And yes, it uses the OpenWrt ImageBuilder to create images.

**Comment by castillofrancodamian** [comment]
Still, I don't have a real need to have my own server. It was just to test.
