### ISSUE TITLE
Sysupgrade fail for x86_64

### ISSUE THREAD

**Issue by xtendpayaa** [openwrt/asu#318]
Hi!
Full paste is here: https://fckthat.site/paste/view/12746c20
But last few lines with error:
`Downloading file:packages/Packages
Updated list of available packages in /home/aparcar/asu/worker1/cache/21.02.2/x86/64/build_dir/target-x86_64_musl/root-x86/../../../../../../../../../../../home/aparcar/asu/worker1/cache/21.02.2/x86/64/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check failed.
Remove wrong Signature file.
Pseudo file "/dev" exists in source filesystem "/home/aparcar/asu/worker1/cache/21.02.2/x86/64/build_dir/target-x86_64_musl/root-x86/dev".
Ignoring, exclude it (-e/-ef) to override.
error: ext4_allocate_best_fit_partial: failed to allocate 6 blocks, out of space?
make[3]: *** [/home/aparcar/asu/worker1/cache/21.02.2/x86/64/include/image.mk:334: /home/aparcar/asu/worker1/cache/21.02.2/x86/64/build_dir/target-x86_64_musl/linux-x86_64/root.ext4] Error 1
make[2]: *** [Makefile:186: build_image] Error 2
make[1]: *** [Makefile:124: _call_image] Error 2
make: *** [Makefile:240: image] Error 2`

I remember when I used the image builder I get the same error but solved with CONFIG_TARGET_KERNEL_PARTSIZE=...
CONFIG_TARGET_ROOTFS_PARTSIZE=... change to bigger. But here I can't change this values.

**Comment by aparcar** [comment]
@dangowrt do you have an idea for this? technically the client could request a specific size however this likely ruins caching.

**Comment by aparcar** [comment]
Well what do in this case? It's not possible to disable ext4 for the image builder or is it?

**Comment by xtendpayaa** [comment]
Thank you guys for helping me. Yeah I would use only squashfs-combined.img (like the current os)

**Comment by dangowrt** [comment]
It is possible to patch `.config` in the IB to enable/disable filesystems to be generated. 
```
sed -i 's/^.*CONFIG_TARGET_ROOTFS_EXT4FS.*$/# CONFIG_TARGET_ROOTFS_EXT4FS is not set/' .config
```
Not the most convenient API, but you can hence select only ext4, jffs2, squashfs and ubifs, depending on what the client requested.

**Comment by aparcar** [comment]
@dangowrt is it possible to sysupgrade a ext4 image without loosing data?

**Comment by dangowrt** [comment]
Yes, sysupgrade on ext4 potentially works just as well as with squashfs, ie. modified configuration files will be kept by default. More advanced options, like keeping **all** modified files or features like **factory reset** are unavailable, of course, as there is no overlayfs then. I don't think you should unconditionally disable ext4 -- I did argue for this in the past, but now we have build all the tooling to make clients automatically request the image with rootfs type currently running, and that required changes to `rpcd`, `procd` and `auc` (and probably the LuCI app as well). Dropping it now again in favor of just always using squashfs is of course still an option, but we should have just done this 2 years ago (and now we shall then revert/remove some things we added to OpenWrt just supporting asu with ext4, jffs2 and ubifs rootfs)

**Comment by aparcar** [comment]
Fair, I'll implement that.

**Comment by ziruizhuang** [comment]
Similar issue here 
```error: ext4_allocate_best_fit_partial: failed to allocate 623 blocks, out of space?
make[3]: *** [/home/user/asu/cache/21.02.3/x86/64/include/image.mk:334: /home/user/asu/cache/21.02.3/x86/64/build_dir/target-x86_64_musl/linux-x86_64/root.ext4] Error 1
make[2]: *** [Makefile:186: build_image] Error 2
make[1]: *** [Makefile:124: _call_image] Error 2
make: *** [Makefile:240: image] Error 2
```

It is possible that the LuCI client requested a quite large image, 

```Building images...
Creating filesystem with parameters:
    Size: 109051904
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 6656
    Inode size: 256
    Journal blocks: 0
    Label: rootfs
    Blocks: 26624
    Block groups: 1
    Reserved blocks: 0
    Reserved block group size: 7
```
Yet I setup a local ASU server with sufficient spare disk space available. Still trying to pin point the problem.

It was a successful upgrade from 21.02.1 to 21.02.2 (using sysupgrade.openwrt.org server). I just cannot recall if it is before or after I resized the partition to a that large size.
