### ISSUE TITLE
Attended sysupgrade notfounderror

### ISSUE THREAD

**Issue by ScooterNC** [openwrt/asu#332]
I recently installed openwrt and ran attended sysupgrade and it worked.  After that I get notfounderror and resource not found whenever I click attended sysupgrade.

**Comment by githubbapoopa** [comment]
I second this.

**Comment by aparcar** [comment]
Fixed via https://github.com/openwrt/luci/commit/65266c490a40e589bde23acb1bcac401813c43ce
