### ISSUE TITLE
fail in sysupgrade SNAPSHOT - r19086-802df09873

### ISSUE THREAD

**Issue by loopoor** [openwrt/asu#335]
Hi, I had a sysupgrade on a rpi4 that fail on the end with Make... (in LuCi)
Any comment?

**Comment by aparcar** [comment]
Could you please give more details? The LuCI app should give your further details on the build requests and the error message.

**Comment by aparcar** [comment]
I'll close this since I'm missing further information. If the problem persists I'm happy to assist
