### ISSUE TITLE
Server response: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by rossiniscarface** [openwrt/asu#350]
`{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r16495-bf0c965af0",
    "advanced_mode": "0",
    "app_version": "git-22.090.55699-bb6ef9f",
    "branch": "21.02",
    "efi": null,
    "profile": "netgear,wndr3800",
    "target": "ath79/generic",
    "version": "21.02.3",
    "packages": [
        "auc",
        "base-files",
        "busybox",
        "ca-bundle",
        "dnsmasq",
        "dropbear",
        "firewall",
        "fstools",
        "ip6tables",
        "iptables",
        "kernel",
        "kmod-ath9k",
        "kmod-gpio-button-hotplug",
        "kmod-ipt-offload",
        "kmod-leds-reset",
        "kmod-owl-loader",
        "kmod-usb-ledtrig-usbport",
        "kmod-usb-ohci",
        "kmod-usb2",
        "libc",
        "libustream-wolfssl",
        "logd",
        "luci",
        "luci-app-attendedsysupgrade",
        "mtd",
        "netifd",
        "odhcp6c",
        "odhcpd-ipv6only",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "swconfig",
        "uboot-envtools",
        "ucert",
        "uci",
        "uclient-fetch",
        "urandom-seed",
        "urngd",
        "wpad-mesh-wolfssl"
    ],
    "diff_packages": true,
    "filesystem": "squashfs"
}`

**Comment by m0dul8r** [comment]
{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r19605-203ffc4ca7",
    "advanced_mode": "0",
    "app_version": "git-22.081.81213-8936e3c",
    "branch": "SNAPSHOT",
    "efi": null,
    "profile": "linksys,e8450-ubi",
    "target": "mediatek/mt7622",
    "version": "SNAPSHOT",
    "packages": [
        "auc",
        "base-files",
        "busybox",
        "ca-bundle",
        "curl",
        "dnscrypt-proxy2",
        "dnsmasq",
        "dropbear",
        "firewall",
        "fstools",
        "fwtool",
        "getrandom",
        "hostapd-common",
        "ip6tables-legacy",
        "iptables-legacy",
        "iw",
        "iwinfo",
        "jansson",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-cfg80211",
        "kmod-crypto-aead",
        "kmod-crypto-ccm",
        "kmod-crypto-cmac",
        "kmod-crypto-crc32c",
        "kmod-crypto-ctr",
        "kmod-crypto-gcm",
        "kmod-crypto-gf128",
        "kmod-crypto-ghash",
        "kmod-crypto-hash",
        "kmod-crypto-hmac",
        "kmod-crypto-manager",
        "kmod-crypto-null",
        "kmod-crypto-rng",
        "kmod-crypto-seqiv",
        "kmod-crypto-sha256",
        "kmod-gpio-button-hotplug",
        "kmod-hwmon-core",
        "kmod-leds-gpio",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc32c",
        "kmod-mac80211",
        "kmod-mt76-connac",
        "kmod-mt76-core",
        "kmod-mt7615-common",
        "kmod-mt7615-firmware",
        "kmod-mt7615e",
        "kmod-mt7915e",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-nat",
        "kmod-nf-nat6",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nfnetlink",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-slhc",
        "kmod-usb3",
        "libblobmsg-json",
        "libc",
        "libiwinfo",
        "libiwinfo-data",
        "libjson-c",
        "libjson-script",
        "libmnl",
        "libnftnl",
        "libnl-tiny",
        "libopenssl",
        "libopenssl-conf",
        "libubox",
        "libubus",
        "libuci",
        "libuclient",
        "libucode",
        "libustream-mbedtls",
        "libwolfssl",
        "logd",
        "luci",
        "luci-app-attendedsysupgrade",
        "luci-app-banip",
        "luci-app-cshark",
        "luci-app-firewall",
        "luci-app-uhttpd",
        "luci-base",
        "luci-lib-jsonc",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-theme-bootstrap",
        "msmtp",
        "mtd",
        "netifd",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openssl-util",
        "openwrt-keyring",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "ubi-utils",
        "uboot-envtools",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "ucode",
        "ucode-mod-fs",
        "ucode-mod-ubus",
        "ucode-mod-uci",
        "uhttpd",
        "urandom-seed",
        "urngd",
        "usign",
        "wireless-regdb",
        "wpad-basic-wolfssl"
    ],
    "diff_packages": true,
    "filesystem": "squashfs"
}

**Comment by maj113** [comment]
same issue here

**Comment by anatol** [comment]
I have the same problem at `21.02.1 r16325-88151b8303 on ipq806x/generic (netgear,r7800)`

**Comment by cosminsstoica** [comment]
same for rpi4 and tplink wdr4900v1

**Comment by m0dul8r** [comment]
This is 100% a server issue at https://sysupgrade.openwrt.org/  .  I temporarily switched the build server to https://asu.aparcar.org/ and it worked for me.

**Comment by aparcar** [comment]
Hey, thanks for reporting. The servers storage ran out, I cleaned up some older ImageBuilders, should work again.

**Comment by rossiniscarface** [comment]
jup. works again
