### ISSUE TITLE
From 21.x to 22.x

### ISSUE THREAD

**Issue by StSaens** [openwrt/asu#351]
As far as I see I can't use this package to do a major upgrade to a new release. 

Is this correct? And if so, is this in the pipeline?

**Comment by aparcar** [comment]
It is possible but since 22.03 is not officially released yet (only release candidates) the tools doesn't notify you about the version

**Comment by StSaens** [comment]
Right. Thanks.
Maybe a feature to allow upgrade to RC's. A flag under the advanced options or something, maybe?

All in all, great package.

**Comment by StSaens** [comment]
> I've noticed that you can choose the 22.xx RC version, if you have enabled the "advanced mode" under configuration. However then you need to add the firewall4 packages and remove the previouse. If you leave it as is, you get [#347 (comment)](https://github.com/openwrt/asu/issues/347#issue-1215993338).
> I didn't tried messing with the packages. Good luck!

I’m assuming this is NOT from the Luci app?
I was meaning using the Luci app. Sorry I wasn’t clear.

**Comment by Underworld6** [comment]
It is from Luci. 
![Screenshot_20220525-135601_Chrome](https://user-images.githubusercontent.com/104441636/170246753-4faa92bf-d03c-422f-99f0-205607061298.jpg)

**Comment by StSaens** [comment]
Odd I don't see 22 rc when I enable these settings:

![image](https://user-images.githubusercontent.com/11319160/170250194-d0058e8c-6def-474c-b4d5-a2915a23404d.png)

**Comment by aparcar** [comment]
At this point you can't switch from a SNAPSHOT version to a RC or stable version since it's likely a downgrade.

**Comment by aparcar** [comment]
For reference, if you want to use the CLI to upgrade to a pre-release, use `auc -b 21.02 -B 21.02-SNAPSHOT`
