### ISSUE TITLE
opkg_install_cmd: Cannot install package kmod-crypto-lib-blake2s.

### ISSUE THREAD

**Issue by StSaens** [openwrt/asu#362]
Getting an impossible package selection error.

`{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r19312-1b7cf4dd1c",
    "advanced_mode": "0",
    "app_version": "git-22.068.37885-65266c4",
    "branch": "22.03",
    "efi": null,
    "rootfs_type": "squashfs",
    "profile": "netgear,r7800",
    "target": "ipq806x/generic",
    "version": "22.03-SNAPSHOT",
    "packages": [
        "6in4",
        "6rd",
        "6to4",
        "ath10k-board-qca9984",
        "ath10k-firmware-qca9984-ct",
        "base-files",
        "block-mount",
        "busybox",
        "ca-bundle",
        "ca-certificates",
        "ccrypt",
        "cgi-io",
        "collectd",
        "collectd-mod-conntrack",
        "collectd-mod-cpu",
        "collectd-mod-cpufreq",
        "collectd-mod-dhcpleases",
        "collectd-mod-entropy",
        "collectd-mod-exec",
        "collectd-mod-interface",
        "collectd-mod-iwinfo",
        "collectd-mod-load",
        "collectd-mod-memory",
        "collectd-mod-network",
        "collectd-mod-ping",
        "collectd-mod-rrdtool",
        "collectd-mod-thermal",
        "collectd-mod-uptime",
        "curl",
        "diffutils",
        "dropbear",
        "firewall4",
        "fstools",
        "fwtool",
        "gdbserver",
        "getrandom",
        "hostapd-common",
        "hostapd-utils",
        "htop",
        "ip6tables-nft",
        "iptables-mod-ipopt",
        "iptables-mod-ipsec",
        "iptables-nft",
        "irqbalance",
        "iw",
        "iwinfo",
        "jansson",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-ata-ahci",
        "kmod-ata-ahci-platform",
        "kmod-ata-core",
        "kmod-ath",
        "kmod-ath10k-ct",
        "kmod-cdrom",
        "kmod-cfg80211",
        "kmod-chaoskey",
        "kmod-crypto-aead",
        "kmod-crypto-arc4",
        "kmod-crypto-ccm",
        "kmod-crypto-cmac",
        "kmod-crypto-crc32c",
        "kmod-crypto-ctr",
        "kmod-crypto-des",
        "kmod-crypto-ecb",
        "kmod-crypto-gcm",
        "kmod-crypto-gf128",
        "kmod-crypto-ghash",
        "kmod-crypto-hash",
        "kmod-crypto-hmac",
        "kmod-crypto-kpp",
        "kmod-crypto-lib-blake2s",
        "kmod-crypto-lib-chacha20",
        "kmod-crypto-lib-chacha20poly1305",
        "kmod-crypto-lib-curve25519",
        "kmod-crypto-lib-poly1305",
        "kmod-crypto-manager",
        "kmod-crypto-md4",
        "kmod-crypto-md5",
        "kmod-crypto-null",
        "kmod-crypto-rng",
        "kmod-crypto-seqiv",
        "kmod-crypto-sha1",
        "kmod-crypto-sha256",
        "kmod-crypto-sha512",
        "kmod-fs-cifs",
        "kmod-fs-exfat",
        "kmod-fs-ext4",
        "kmod-fs-hfsplus",
        "kmod-fs-msdos",
        "kmod-fs-vfat",
        "kmod-fuse",
        "kmod-gpio-button-hotplug",
        "kmod-gre",
        "kmod-hwmon-core",
        "kmod-ifb",
        "kmod-ip6tables",
        "kmod-ipt-core",
        "kmod-ipt-ipopt",
        "kmod-ipt-ipsec",
        "kmod-iptunnel",
        "kmod-iptunnel4",
        "kmod-leds-gpio",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc16",
        "kmod-lib-crc32c",
        "kmod-mac80211",
        "kmod-mppe",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack-netlink",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-ipt",
        "kmod-nf-ipt6",
        "kmod-nf-log",
        "kmod-nf-log6",
        "kmod-nf-nat",
        "kmod-nf-nat6",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nfnetlink",
        "kmod-nft-compat",
        "kmod-nft-core",
        "kmod-nft-fib",
        "kmod-nft-nat",
        "kmod-nft-nat6",
        "kmod-nft-offload",
        "kmod-nls-base",
        "kmod-nls-cp1250",
        "kmod-nls-cp437",
        "kmod-nls-cp850",
        "kmod-nls-iso8859-1",
        "kmod-nls-iso8859-15",
        "kmod-nls-utf8",
        "kmod-phy-qcom-ipq806x-usb",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-pptp",
        "kmod-pstore",
        "kmod-ramoops",
        "kmod-random-core",
        "kmod-reed-solomon",
        "kmod-sched-bpf",
        "kmod-sched-cake",
        "kmod-sched-core",
        "kmod-scsi-core",
        "kmod-sit",
        "kmod-slhc",
        "kmod-tun",
        "kmod-udptunnel4",
        "kmod-udptunnel6",
        "kmod-usb-core",
        "kmod-usb-dwc3",
        "kmod-usb-dwc3-qcom",
        "kmod-usb-ehci",
        "kmod-usb-ledtrig-usbport",
        "kmod-usb-ohci",
        "kmod-usb-storage",
        "kmod-usb-xhci-hcd",
        "kmod-usb2",
        "kmod-usb3",
        "libblkid",
        "libblobmsg-json",
        "libc",
        "libcurl",
        "libiptext",
        "libiptext-nft",
        "libiptext6",
        "libiwinfo",
        "libiwinfo-data",
        "libiwinfo-lua",
        "libjson-c",
        "libjson-script",
        "libltdl",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "libmnl",
        "libncurses",
        "libnftnl",
        "libnghttp2",
        "libnl-tiny",
        "libopenssl",
        "libopenssl-conf",
        "liboping",
        "libpcap",
        "libpcre",
        "librrd1",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuci-lua",
        "libuclient",
        "libucode",
        "libustream-openssl",
        "libuuid",
        "libxtables",
        "logd",
        "lua",
        "luci",
        "luci-app-attendedsysupgrade",
        "luci-app-commands",
        "luci-app-firewall",
        "luci-app-opkg",
        "luci-app-uhttpd",
        "luci-base",
        "luci-compat",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-mod-admin-full",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-proto-ipv6",
        "luci-proto-ppp",
        "luci-ssl-openssl",
        "luci-theme-bootstrap",
        "luci-theme-material",
        "luci-theme-openwrt-2020",
        "mtd",
        "mtr-nojson",
        "nano-full",
        "netifd",
        "nftables-json",
        "ntfs-3g",
        "odhcp6c",
        "openssl-util",
        "openwrt-keyring",
        "opkg",
        "patch",
        "ppp",
        "ppp-mod-pppoe",
        "ppp-mod-pptp",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "resolveip",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-iwinfo",
        "rpcd-mod-luci",
        "rpcd-mod-rrdns",
        "speedtest-netperf",
        "swconfig",
        "tcpdump-mini",
        "terminfo",
        "tree",
        "ubi-utils",
        "uboot-envtools",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "ucode",
        "ucode-mod-fs",
        "ucode-mod-ubus",
        "ucode-mod-uci",
        "uhttpd",
        "uhttpd-mod-ubus",
        "urandom-seed",
        "urngd",
        "usign",
        "wget-ssl",
        "wireless-regdb",
        "wpad-openssl",
        "xtables-nft",
        "zlib"
    ],
    "diff_packages": true
} `

`Package list missing or not up-to-date, generating it.

Building package index...
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/targets/ipq806x/generic/packages/Packages.gz
Updated list of available packages in /home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../../../../../../../../home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/dl/openwrt_core
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/targets/ipq806x/generic/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/base/Packages.gz
Updated list of available packages in /home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../../../../../../../../home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/dl/openwrt_base
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/targets/ipq806x/generic/kmods/5.10.120-1-16163c1acbad5a83015a1208dd041320/Packages.gz
Updated list of available packages in /home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../../../../../../../../home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/dl/openwrt_kmods
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/targets/ipq806x/generic/kmods/5.10.120-1-16163c1acbad5a83015a1208dd041320/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/luci/Packages.gz
Updated list of available packages in /home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../../../../../../../../home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/dl/openwrt_luci
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/packages/Packages.gz
Updated list of available packages in /home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../../../../../../../../home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/dl/openwrt_packages
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/routing/Packages.gz
Updated list of available packages in /home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../../../../../../../../home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/dl/openwrt_routing
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/telephony/Packages.gz
Updated list of available packages in /home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../../../../../../../../home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/dl/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/22.03-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/telephony/Packages.sig
Signature check passed.
Downloading file:packages/Packages
Updated list of available packages in /home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../../../../../../../../home/aparcar/asu/worker2/cache/22.03-SNAPSHOT/ipq806x/generic/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check failed.
Remove wrong Signature file.
Collected errors:
 * opkg_install_cmd: Cannot install package kmod-crypto-lib-blake2s.
make[2]: *** [Makefile:169: package_install] Error 255
make[1]: *** [Makefile:134: _call_manifest] Error 2
make: *** [Makefile:253: manifest] Error 2 `

**Comment by StSaens** [comment]
Found this: https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=cd634afe6cb6565eb6865931c8d73d97cab3600a
But I don't fully understand if upgrading the router without this lib breaks anything. Doesn't seem to be related to asu.

**Comment by aparcar** [comment]
> as BLAKE2s is now built-in

Looks like you can just remove it.

**Comment by mmokrejs** [comment]
```
Error building the firmware image

Server response: Unsupported package(s): kmod-crypto-lib-blake2s
[Please report the error message and request](https://github.com/openwrt/asu/issues)

Request Data:

{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r16554-1d4dea6d4f",
    "advanced_mode": "0",
    "branch": "21.02",
    "efi": null,
    "profile": "netgear,r7800",
    "target": "ipq806x/generic",
    "version": "21.02.5",
    "packages": [
        "acme-dnsapi",
        "ath10k-board-qca9984",
        "ath10k-firmware-qca9984-ct",
        "base-files",
        "busybox",
        "ca-bundle",
        "cgi-io",
        "cryptsetup",
        "cryptsetup-ssh",
        "diffutils",
        "dnsmasq",
        "dropbear",
        "firewall",
        "fstools",
        "fwtool",
        "getrandom",
        "hostapd-common",
        "ip-bridge",
        "ip6tables",
        "ip6tables-mod-nat",
        "iptables",
        "iw",
        "iwinfo",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-ata-ahci",
        "kmod-ata-ahci-platform",
        "kmod-ata-core",
        "kmod-ath",
        "kmod-ath10k-ct",
        "kmod-cfg80211",
        "kmod-crypto-acompress",
        "kmod-crypto-arc4",
        "kmod-crypto-authenc",
        "kmod-crypto-cbc",
        "kmod-crypto-ccm",
        "kmod-crypto-cmac",
        "kmod-crypto-crc32",
        "kmod-crypto-crc32c",
        "kmod-crypto-cts",
        "kmod-crypto-deflate",
        "kmod-crypto-des",
        "kmod-crypto-ecb",
        "kmod-crypto-ecdh",
        "kmod-crypto-echainiv",
        "kmod-crypto-fcrypt",
        "kmod-crypto-gcm",
        "kmod-crypto-hw-geode",
        "kmod-crypto-hw-hifn-795x",
        "kmod-crypto-hw-padlock",
        "kmod-crypto-hw-talitos",
        "kmod-crypto-lib-blake2s",
        "kmod-crypto-lib-chacha20",
        "kmod-crypto-lib-chacha20poly1305",
        "kmod-crypto-lib-curve25519",
        "kmod-crypto-md4",
        "kmod-crypto-md5",
        "kmod-crypto-michael-mic",
        "kmod-crypto-misc",
        "kmod-crypto-pcbc",
        "kmod-crypto-rmd160",
        "kmod-crypto-rng",
        "kmod-crypto-seqiv",
        "kmod-crypto-sha1",
        "kmod-crypto-sha256",
        "kmod-crypto-sha512",
        "kmod-crypto-test",
        "kmod-crypto-wq",
        "kmod-crypto-xcbc",
        "kmod-crypto-xts",
        "kmod-fs-exfat",
        "kmod-fs-ext4",
        "kmod-fuse",
        "kmod-gpio-button-hotplug",
        "kmod-hid",
        "kmod-hwmon-core",
        "kmod-ip6tables",
        "kmod-ipt-conntrack",
        "kmod-ipt-core",
        "kmod-ipt-nat",
        "kmod-ipt-offload",
        "kmod-leds-gpio",
        "kmod-lib-crc-ccitt",
        "kmod-lib-lz4",
        "kmod-lib-lzo",
        "kmod-lib-zlib-deflate",
        "kmod-lib-zlib-inflate",
        "kmod-mac80211",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-ipt",
        "kmod-nf-ipt6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nls-base",
        "kmod-phy-qcom-ipq806x-usb",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-scsi-core",
        "kmod-scsi-generic",
        "kmod-slhc",
        "kmod-usb-core",
        "kmod-usb-dwc3",
        "kmod-usb-dwc3-qcom",
        "kmod-usb-ehci",
        "kmod-usb-ledtrig-usbport",
        "kmod-usb-ohci",
        "kmod-usb-storage",
        "kmod-usb-storage-uas",
        "kmod-usb-uhci",
        "kmod-usb2",
        "kmod-usb3",
        "libblobmsg-json",
        "libc",
        "libdevmapper",
        "libexpat",
        "libgpg-error",
        "libip4tc",
        "libip6tc",
        "libiwinfo",
        "libiwinfo-data",
        "libiwinfo-lua",
        "libjson-c",
        "libjson-script",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "libmbim",
        "libnl-tiny",
        "libopenssl",
        "libopenssl-conf",
        "libopenssl-devcrypto",
        "libprotobuf-c",
        "libqmi",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuclient",
        "libustream-wolfssl",
        "libwolfssl",
        "libxml2",
        "libxtables",
        "logd",
        "lsof",
        "lua",
        "luci",
        "luci-app-acl",
        "luci-app-acme",
        "luci-app-attendedsysupgrade",
        "luci-app-diag-core",
        "luci-app-firewall",
        "luci-app-mwan3",
        "luci-app-ntpc",
        "luci-app-ocserv",
        "luci-app-openvpn",
        "luci-app-opkg",
        "luci-app-squid",
        "luci-app-statistics",
        "luci-app-upnp",
        "luci-app-xinetd",
        "luci-base",
        "luci-compat",
        "luci-i18n-attendedsysupgrade-en",
        "luci-i18n-upnp-en",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-mod-system",
        "luci-proto-3g",
        "luci-proto-ipip",
        "luci-proto-modemmanager",
        "luci-proto-ncm",
        "luci-proto-openconnect",
        "luci-proto-qmi",
        "luci-proto-vpnc",
        "luci-theme-bootstrap",
        "lvm2",
        "miniupnpc",
        "miniupnpd",
        "modemmanager",
        "mtd",
        "mwan3",
        "netcat",
        "netifd",
        "nmap-ssl",
        "ocserv",
        "odhcp6c",
        "openconnect",
        "openssh-sftp-client",
        "openssh-sftp-server",
        "openvpn-openssl",
        "openwrt-keyring",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-luci",
        "sshfs",
        "strace",
        "swconfig",
        "syncthing",
        "tinc",
        "ubi-utils",
        "uboot-envtools",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "urandom-seed",
        "urngd",
        "usign",
        "vpnc",
        "vsftpd-tls",
        "wireless-regdb",
        "wpad-basic-wolfssl",
        "zlib"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-22.210.54423-3b0b325"
}
```
