### ISSUE TITLE
22.03 requests currently broken

### ISSUE THREAD

**Issue by aparcar** [openwrt/asu#375]
Due to upstream issues described [here](https://github.com/openwrt/openwrt/pull/10329) all images for 22.03 are currently broken. Please wait until the issue is fixed before reporting the error here.

**Comment by aparcar** [comment]
Fixed via https://github.com/openwrt/openwrt/commit/8b6b73d0e895bbbfc448bea9fb5f3751593d7865

**Comment by neheb** [comment]
you should unpin this.

**Comment by sirweazel** [comment]
Comment says fixed and closed on Aug 2. I might not understand the SSL problem though. Do i need to update the luci-app-attendedsysupgrade package for the fix to apply?  Currently when checking for an update, i do not get any available. 

![image](https://user-images.githubusercontent.com/24688999/189557632-3617f867-ca0f-40c5-90b7-7a995a38054b.png)
![image](https://user-images.githubusercontent.com/24688999/189557700-19b64445-ee43-47c0-8ae7-f0dae1a132b7.png)
![image](https://user-images.githubusercontent.com/24688999/189557749-5b9c1547-d1fe-4055-9c52-53d39540f827.png)
