### ISSUE TITLE
Unsupported package(s): luci-app-argon-config, luci-app-adguardhome, luci-theme-argon

### ISSUE THREAD

**Issue by mfrazzz** [openwrt/asu#385]
Getting the following.  I guess the Argon theme isn't surprising but the luci-app-adguardhome is.

Server response: Unsupported package(s): luci-app-argon-config, luci-app-adguardhome, luci-theme-argon

{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r16279-5cc0535800",
    "advanced_mode": "1",
    "branch": "21.02",
    "efi": null,
    "profile": "raspberrypi,4-model-b",
    "target": "bcm27xx/bcm2711",
    "version": "21.02.3",
    "packages": [
        "base-files",
        "bcm27xx-gpu-fw",
        "bcm27xx-userland",
        "bind-host",
        "bind-libs",
        "block-mount",
        "brcmfmac-firmware-usb",
        "busybox",
        "ca-bundle",
        "ca-certificates",
        "cgi-io",
        "curl",
        "cypress-firmware-43455-sdio",
        "cypress-nvram-43455-sdio-rpi-4b",
        "ddns-scripts",
        "ddns-scripts-services",
        "dnsmasq",
        "dropbear",
        "e2fsprogs",
        "f2fs-tools",
        "fdisk",
        "firewall",
        "fstools",
        "fwtool",
        "gdisk",
        "getrandom",
        "hostapd-common",
        "ip6tables",
        "iptables",
        "iw",
        "iwinfo",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-brcmfmac",
        "kmod-fs-ext4",
        "kmod-fs-f2fs",
        "kmod-fs-vfat",
        "kmod-hid",
        "kmod-hid-generic",
        "kmod-input-core",
        "kmod-input-evdev",
        "kmod-ip6tables",
        "kmod-ipt-conntrack",
        "kmod-ipt-core",
        "kmod-ipt-nat",
        "kmod-ipt-offload",
        "kmod-lib-crc-ccitt",
        "kmod-mii",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-ipt",
        "kmod-nf-ipt6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nls-base",
        "kmod-nls-cp437",
        "kmod-nls-iso8859-1",
        "kmod-nls-utf8",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-slhc",
        "kmod-sound-arm-bcm2835",
        "kmod-sound-core",
        "kmod-usb-core",
        "kmod-usb-hid",
        "kmod-usb-net",
        "kmod-usb-net-rtl8152",
        "libblkid",
        "libblobmsg-json",
        "libcomerr",
        "libcurl",
        "libext2fs",
        "libf2fs",
        "libip4tc",
        "libip6tc",
        "libiwinfo",
        "libiwinfo-data",
        "libiwinfo-lua",
        "libjson-c",
        "libjson-script",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "libncurses",
        "libnl-tiny",
        "libopenssl",
        "libsmartcols",
        "libss",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuclient",
        "libustream-wolfssl",
        "libuuid",
        "libwolfssl",
        "libxtables",
        "logd",
        "lua",
        "luci",
        "luci-app-adguardhome",
        "luci-app-argon-config",
        "luci-app-attendedsysupgrade",
        "luci-app-ddns",
        "luci-app-firewall",
        "luci-app-opkg",
        "luci-app-sqm",
        "luci-app-uhttpd",
        "luci-app-upnp",
        "luci-base",
        "luci-compat",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-mod-admin-full",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-proto-ipv6",
        "luci-proto-ppp",
        "luci-ssl",
        "luci-theme-argon",
        "luci-theme-bootstrap",
        "mkf2fs",
        "mtd",
        "netifd",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openwrt-keyring",
        "opkg",
        "partx-utils",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "px5g-wolfssl",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-iwinfo",
        "rpcd-mod-luci",
        "rpcd-mod-rrdns",
        "terminfo",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "uhttpd",
        "uhttpd-mod-ubus",
        "unzip",
        "urandom-seed",
        "usign",
        "wget-ssl",
        "wireless-regdb",
        "wpad-basic-wolfssl",
        "zlib"
    ],
    "diff_packages": true,
    "filesystem": "ext4",
    "client": "luci/git-22.210.54423-3b0b325"
}

**Comment by aparcar** [comment]
If your package is not part of upstream it can't be added https://github.com/openwrt/luci/pull/5853
