### ISSUE TITLE
Error building the firmware image

### ISSUE THREAD

**Issue by Firebrand-mx** [openwrt/asu#412]
Server response: Unsupported package(s): luci-app-tn-netports, luci-app-temp-status, luci-app-log, luci-app-cpu-status, luci-app-adguardhome, luci-app-interfaces-statistics

Request Data:

{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r21022+9-9226f1e419",
    "advanced_mode": "1",
    "branch": "SNAPSHOT",
    "efi": null,
    "profile": "linksys,wrt3200acm",
    "target": "mvebu/cortexa9",
    "version": "SNAPSHOT",
    "packages": [
        "acme",
        "acme-acmesh",
        "acme-common",
        "adblock",
        "attendedsysupgrade-common",
        "base-files",
        "bash",
        "bcp38",
        "bind-host",
        "bind-libs",
        "block-mount",
        "bmon",
        "btrfs-progs",
        "busybox",
        "bzip2",
        "ca-bundle",
        "ca-certificates",
        "cgi-io",
        "confuse",
        "coreutils",
        "coreutils-sort",
        "coreutils-stat",
        "curl",
        "ddns-scripts",
        "ddns-scripts-services",
        "dropbear",
        "e2fsprogs",
        "fstools",
        "fstrim",
        "fwtool",
        "getrandom",
        "hostapd-common",
        "htop",
        "ip-bridge",
        "ip-full",
        "ip-tiny",
        "iperf3",
        "ipset",
        "iptables-mod-conntrack-extra",
        "iptables-mod-hashlimit",
        "iptables-mod-ipopt",
        "iptables-mod-iprange",
        "iptables-mod-socket",
        "iptables-mod-tproxy",
        "iptables-zz-legacy",
        "iw",
        "iwinfo",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-ata-core",
        "kmod-bluetooth",
        "kmod-btmrvl",
        "kmod-cfg80211",
        "kmod-crypto-acompress",
        "kmod-crypto-aead",
        "kmod-crypto-authenc",
        "kmod-crypto-ccm",
        "kmod-crypto-cmac",
        "kmod-crypto-crc32c",
        "kmod-crypto-ctr",
        "kmod-crypto-ecb",
        "kmod-crypto-ecdh",
        "kmod-crypto-gcm",
        "kmod-crypto-gf128",
        "kmod-crypto-ghash",
        "kmod-crypto-hash",
        "kmod-crypto-hmac",
        "kmod-crypto-kpp",
        "kmod-crypto-lib-chacha20",
        "kmod-crypto-lib-chacha20poly1305",
        "kmod-crypto-lib-curve25519",
        "kmod-crypto-lib-poly1305",
        "kmod-crypto-manager",
        "kmod-crypto-null",
        "kmod-crypto-rng",
        "kmod-crypto-seqiv",
        "kmod-crypto-sha256",
        "kmod-cryptodev",
        "kmod-fs-btrfs",
        "kmod-fs-ext4",
        "kmod-fuse",
        "kmod-gpio-button-hotplug",
        "kmod-hid",
        "kmod-ifb",
        "kmod-input-core",
        "kmod-input-evdev",
        "kmod-ip6tables",
        "kmod-ipt-conntrack",
        "kmod-ipt-conntrack-extra",
        "kmod-ipt-core",
        "kmod-ipt-hashlimit",
        "kmod-ipt-ipopt",
        "kmod-ipt-iprange",
        "kmod-ipt-ipset",
        "kmod-ipt-nat",
        "kmod-ipt-offload",
        "kmod-ipt-raw",
        "kmod-ipt-socket",
        "kmod-ipt-tproxy",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc16",
        "kmod-lib-crc32c",
        "kmod-lib-lzo",
        "kmod-lib-raid6",
        "kmod-lib-textsearch",
        "kmod-lib-xor",
        "kmod-lib-zlib-deflate",
        "kmod-lib-zlib-inflate",
        "kmod-lib-zstd",
        "kmod-mac80211",
        "kmod-mii",
        "kmod-mmc",
        "kmod-mwifiex-sdio",
        "kmod-mwlwifi",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack-netlink",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-ipt",
        "kmod-nf-ipt6",
        "kmod-nf-log",
        "kmod-nf-log6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nf-socket",
        "kmod-nf-tproxy",
        "kmod-nfnetlink",
        "kmod-nft-core",
        "kmod-nft-nat",
        "kmod-nft-offload",
        "kmod-nls-base",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-regmap-core",
        "kmod-sched",
        "kmod-sched-cake",
        "kmod-sched-connmark",
        "kmod-sched-core",
        "kmod-scsi-core",
        "kmod-slhc",
        "kmod-tun",
        "kmod-udptunnel4",
        "kmod-udptunnel6",
        "kmod-usb-core",
        "kmod-usb-net",
        "kmod-usb-net-cdc-ether",
        "kmod-usb-net-ipheth",
        "kmod-usb-net-rndis",
        "kmod-usb-storage",
        "kmod-usb-storage-uas",
        "kmod-veth",
        "kmod-wireguard",
        "libattr",
        "libblkid",
        "libblobmsg-json",
        "libbpf",
        "libbz2",
        "libcap-ng",
        "libcomerr",
        "libcurl",
        "libelf",
        "libevent2",
        "libext2fs",
        "libgmp",
        "libip4tc",
        "libip6tc",
        "libiperf3",
        "libipset",
        "libiptext",
        "libiptext6",
        "libiwinfo",
        "libiwinfo-data",
        "libiwinfo-lua",
        "libjson-c",
        "libjson-script",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "liblzma",
        "liblzo",
        "libmnl",
        "libmount",
        "libncurses",
        "libnetfilter-conntrack",
        "libnettle",
        "libnfnetlink",
        "libnftnl",
        "libnghttp2",
        "libnl-core",
        "libnl-route",
        "libnl-tiny",
        "libopenssl",
        "libopenssl-conf",
        "libopenssl-devcrypto",
        "libpcap",
        "libpcre",
        "libreadline",
        "libsmartcols",
        "libss",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuci-lua",
        "libuclient",
        "libunbound",
        "libustream-openssl",
        "libuuid",
        "libuv",
        "libwolfssl",
        "libxtables",
        "libzstd",
        "logd",
        "lua",
        "luabitop",
        "luci",
        "luci-app-acme",
        "luci-app-adblock",
        "luci-app-adguardhome",
        "luci-app-advanced-reboot",
        "luci-app-attendedsysupgrade",
        "luci-app-bcp38",
        "luci-app-cpu-status",
        "luci-app-ddns",
        "luci-app-interfaces-statistics",
        "luci-app-log",
        "luci-app-opkg",
        "luci-app-qos",
        "luci-app-sqm",
        "luci-app-temp-status",
        "luci-app-tn-netports",
        "luci-app-unbound",
        "luci-app-upnp",
        "luci-app-vpn-policy-routing",
        "luci-app-wireguard",
        "luci-base",
        "luci-compat",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-ipkg",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-mod-admin-full",
        "luci-mod-dashboard",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-proto-ipv6",
        "luci-proto-ppp",
        "luci-proto-wireguard",
        "luci-ssl-openssl",
        "luci-theme-bootstrap",
        "miniupnpd-nftables",
        "mount-utils",
        "mtd",
        "mwifiex-sdio-firmware",
        "mwlwifi-firmware-88w8864",
        "mwlwifi-firmware-88w8964",
        "nano",
        "ncdu",
        "netifd",
        "netperf",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openssl-util",
        "openwrt-keyring",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "qos-scripts",
        "resolveip",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-iwinfo",
        "rpcd-mod-luci",
        "rpcd-mod-rpcsys",
        "rpcd-mod-rrdns",
        "socat",
        "sqm-scripts",
        "tar",
        "tc-full",
        "tc-mod-iptables",
        "tc-tiny",
        "tcpdump",
        "terminfo",
        "tree",
        "tune2fs",
        "ubi-utils",
        "uboot-envtools",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "uhttpd",
        "uhttpd-mod-ubus",
        "unbound-checkconf",
        "unbound-control",
        "unbound-control-setup",
        "unbound-daemon",
        "urandom-seed",
        "urngd",
        "usign",
        "vpn-policy-routing",
        "wget-ssl",
        "wireguard-tools",
        "wireless-regdb",
        "wpad-openssl",
        "xtables-legacy",
        "xz",
        "xz-utils",
        "zlib"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-22.285.67526-18bfcca"
}
Server response: Unsupported package(s): luci-app-tn-netports, luci-app-temp-status, luci-app-log, luci-app-cpu-status, luci-app-adguardhome, luci-app-interfaces-statistics

[Please report the error message and request](https://github.com/openwrt/asu/issues)
Request Data:

{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r21022+9-9226f1e419",
    "advanced_mode": "1",
    "branch": "SNAPSHOT",
    "efi": null,
    "profile": "linksys,wrt3200acm",
    "target": "mvebu/cortexa9",
    "version": "SNAPSHOT",
    "packages": [
        "acme",
        "acme-acmesh",
        "acme-common",
        "adblock",
        "attendedsysupgrade-common",
        "base-files",
        "bash",
        "bcp38",
        "bind-host",
        "bind-libs",
        "block-mount",
        "bmon",
        "btrfs-progs",
        "busybox",
        "bzip2",
        "ca-bundle",
        "ca-certificates",
        "cgi-io",
        "confuse",
        "coreutils",
        "coreutils-sort",
        "coreutils-stat",
        "curl",
        "ddns-scripts",
        "ddns-scripts-services",
        "dropbear",
        "e2fsprogs",
        "fstools",
        "fstrim",
        "fwtool",
        "getrandom",
        "hostapd-common",
        "htop",
        "ip-bridge",
        "ip-full",
        "ip-tiny",
        "iperf3",
        "ipset",
        "iptables-mod-conntrack-extra",
        "iptables-mod-hashlimit",
        "iptables-mod-ipopt",
        "iptables-mod-iprange",
        "iptables-mod-socket",
        "iptables-mod-tproxy",
        "iptables-zz-legacy",
        "iw",
        "iwinfo",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-ata-core",
        "kmod-bluetooth",
        "kmod-btmrvl",
        "kmod-cfg80211",
        "kmod-crypto-acompress",
        "kmod-crypto-aead",
        "kmod-crypto-authenc",
        "kmod-crypto-ccm",
        "kmod-crypto-cmac",
        "kmod-crypto-crc32c",
        "kmod-crypto-ctr",
        "kmod-crypto-ecb",
        "kmod-crypto-ecdh",
        "kmod-crypto-gcm",
        "kmod-crypto-gf128",
        "kmod-crypto-ghash",
        "kmod-crypto-hash",
        "kmod-crypto-hmac",
        "kmod-crypto-kpp",
        "kmod-crypto-lib-chacha20",
        "kmod-crypto-lib-chacha20poly1305",
        "kmod-crypto-lib-curve25519",
        "kmod-crypto-lib-poly1305",
        "kmod-crypto-manager",
        "kmod-crypto-null",
        "kmod-crypto-rng",
        "kmod-crypto-seqiv",
        "kmod-crypto-sha256",
        "kmod-cryptodev",
        "kmod-fs-btrfs",
        "kmod-fs-ext4",
        "kmod-fuse",
        "kmod-gpio-button-hotplug",
        "kmod-hid",
        "kmod-ifb",
        "kmod-input-core",
        "kmod-input-evdev",
        "kmod-ip6tables",
        "kmod-ipt-conntrack",
        "kmod-ipt-conntrack-extra",
        "kmod-ipt-core",
        "kmod-ipt-hashlimit",
        "kmod-ipt-ipopt",
        "kmod-ipt-iprange",
        "kmod-ipt-ipset",
        "kmod-ipt-nat",
        "kmod-ipt-offload",
        "kmod-ipt-raw",
        "kmod-ipt-socket",
        "kmod-ipt-tproxy",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc16",
        "kmod-lib-crc32c",
        "kmod-lib-lzo",
        "kmod-lib-raid6",
        "kmod-lib-textsearch",
        "kmod-lib-xor",
        "kmod-lib-zlib-deflate",
        "kmod-lib-zlib-inflate",
        "kmod-lib-zstd",
        "kmod-mac80211",
        "kmod-mii",
        "kmod-mmc",
        "kmod-mwifiex-sdio",
        "kmod-mwlwifi",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack-netlink",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-ipt",
        "kmod-nf-ipt6",
        "kmod-nf-log",
        "kmod-nf-log6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nf-socket",
        "kmod-nf-tproxy",
        "kmod-nfnetlink",
        "kmod-nft-core",
        "kmod-nft-nat",
        "kmod-nft-offload",
        "kmod-nls-base",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-regmap-core",
        "kmod-sched",
        "kmod-sched-cake",
        "kmod-sched-connmark",
        "kmod-sched-core",
        "kmod-scsi-core",
        "kmod-slhc",
        "kmod-tun",
        "kmod-udptunnel4",
        "kmod-udptunnel6",
        "kmod-usb-core",
        "kmod-usb-net",
        "kmod-usb-net-cdc-ether",
        "kmod-usb-net-ipheth",
        "kmod-usb-net-rndis",
        "kmod-usb-storage",
        "kmod-usb-storage-uas",
        "kmod-veth",
        "kmod-wireguard",
        "libattr",
        "libblkid",
        "libblobmsg-json",
        "libbpf",
        "libbz2",
        "libcap-ng",
        "libcomerr",
        "libcurl",
        "libelf",
        "libevent2",
        "libext2fs",
        "libgmp",
        "libip4tc",
        "libip6tc",
        "libiperf3",
        "libipset",
        "libiptext",
        "libiptext6",
        "libiwinfo",
        "libiwinfo-data",
        "libiwinfo-lua",
        "libjson-c",
        "libjson-script",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "liblzma",
        "liblzo",
        "libmnl",
        "libmount",
        "libncurses",
        "libnetfilter-conntrack",
        "libnettle",
        "libnfnetlink",
        "libnftnl",
        "libnghttp2",
        "libnl-core",
        "libnl-route",
        "libnl-tiny",
        "libopenssl",
        "libopenssl-conf",
        "libopenssl-devcrypto",
        "libpcap",
        "libpcre",
        "libreadline",
        "libsmartcols",
        "libss",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuci-lua",
        "libuclient",
        "libunbound",
        "libustream-openssl",
        "libuuid",
        "libuv",
        "libwolfssl",
        "libxtables",
        "libzstd",
        "logd",
        "lua",
        "luabitop",
        "luci",
        "luci-app-acme",
        "luci-app-adblock",
        "luci-app-adguardhome",
        "luci-app-advanced-reboot",
        "luci-app-attendedsysupgrade",
        "luci-app-bcp38",
        "luci-app-cpu-status",
        "luci-app-ddns",
        "luci-app-interfaces-statistics",
        "luci-app-log",
        "luci-app-opkg",
        "luci-app-qos",
        "luci-app-sqm",
        "luci-app-temp-status",
        "luci-app-tn-netports",
        "luci-app-unbound",
        "luci-app-upnp",
        "luci-app-vpn-policy-routing",
        "luci-app-wireguard",
        "luci-base",
        "luci-compat",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-ipkg",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-mod-admin-full",
        "luci-mod-dashboard",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-proto-ipv6",
        "luci-proto-ppp",
        "luci-proto-wireguard",
        "luci-ssl-openssl",
        "luci-theme-bootstrap",
        "miniupnpd-nftables",
        "mount-utils",
        "mtd",
        "mwifiex-sdio-firmware",
        "mwlwifi-firmware-88w8864",
        "mwlwifi-firmware-88w8964",
        "nano",
        "ncdu",
        "netifd",
        "netperf",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openssl-util",
        "openwrt-keyring",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "qos-scripts",
        "resolveip",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-iwinfo",
        "rpcd-mod-luci",
        "rpcd-mod-rpcsys",
        "rpcd-mod-rrdns",
        "socat",
        "sqm-scripts",
        "tar",
        "tc-full",
        "tc-mod-iptables",
        "tc-tiny",
        "tcpdump",
        "terminfo",
        "tree",
        "tune2fs",
        "ubi-utils",
        "uboot-envtools",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "uhttpd",
        "uhttpd-mod-ubus",
        "unbound-checkconf",
        "unbound-control",
        "unbound-control-setup",
        "unbound-daemon",
        "urandom-seed",
        "urngd",
        "usign",
        "vpn-policy-routing",
        "wget-ssl",
        "wireguard-tools",
        "wireless-regdb",
        "wpad-openssl",
        "xtables-legacy",
        "xz",
        "xz-utils",
        "zlib"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-22.285.67526-18bfcca"
}

**Comment by aparcar** [comment]
You can only request packages that are part of the official feeds. If you have your own packages you need to upstream them or run your own ASU instance.
