### ISSUE TITLE
[generic images] Allow setting of CONFIG_TARGET_ROOTFS_PARTSIZE

### ISSUE THREAD

**Issue by rany2** [openwrt/asu#415]
It would be great if the client could request a custom CONFIG_TARGET_ROOTFS_PARTSIZE so that there would be no need to resize after flashing (or so in case 100MB is somehow not enough for the packages requested).

**Comment by aparcar** [comment]
Agree. This should be part of the upstream IB first

**Comment by rany2** [comment]
Could asu modify `.config` with a regex instead? I'm not sure how the asu works exactly so I'm guessing that's not feasible.

**Comment by aparcar** [comment]
Could you try to create a PR for this? It just needs an addition like [this](https://github.com/openwrt/asu/blob/master/asu/build.py#L275)

**Comment by rany2** [comment]
I'll give it a try. From there I guess the new feature just needs to get used by auc which should be simple enough.

**Comment by joshenders** [comment]
I came here to make this patch after installing a few x86 images and struggling with partition resizing. Have you had a chance to review this PR yet @aparcar?

**Comment by joshenders** [comment]
Happy to see progress here as this has been a thorn in my side for years but has there been any discussion on whether it would make sense to package the x86 release as a small initrd with an installer?
