### ISSUE TITLE
Why has the luci-i18n-wireguard-ru package become unsupported?

### ISSUE THREAD

**Issue by koskem** [openwrt/asu#424]
Ошибка сборки образа прошивки
Ответ сервера: **Unsupported package(s): luci-i18n-wireguard-ru**

[Пожалуйста, сообщите текст ошибки и запроса](https://github.com/openwrt/asu/issues)
Данные запроса:

{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r21335-e410833bdd",
    "advanced_mode": "0",
    "branch": "SNAPSHOT",
    "efi": null,
    "profile": "xiaomi,redmi-router-ax6s",
    "target": "mediatek/mt7622",

**Comment by aparcar** [comment]
All translations were removed via https://github.com/openwrt/luci/commit/6e6fce3eb43ea6899eedc91bebd5713a5d4c773b. Please manually delete the package and try to update again.
