### ISSUE TITLE
Linksys wrt3200acm

### ISSUE THREAD

**Issue by johanengelbrecht** [openwrt/asu#434]
Openwrt does not support Linksys wrt3200acm.

**Comment by HD7544** [comment]
This is by design until the next release of OpenWRT. See https://forum.openwrt.org/t/22-03-x-no-release-builds-for-turris-omnia-linksys-wrt-clearfog/147955 for explanation and alternatives.

**Comment by aparcar** [comment]
Use snapshots for now
