### ISSUE TITLE
Unsupported package(s): ruby-yaml, ruby

### ISSUE THREAD

**Issue by k2p2p** [openwrt/asu#487]
Unsupported package(s): ruby-yaml, ruby

**Comment by aparcar** [comment]
Are those packages in the official feed?

**Comment by k2p2p** [comment]
yes


Paul Spooren ***@***.***> 于 2023年4月20日周四 16:25写道：

**Comment by aparcar** [comment]
What version are you trying to install?

**Comment by k2p2p** [comment]
Versions after 537 have this problem

Paul Spooren ***@***.***> 于 2023年4月20日周四 20:59写道：

**Comment by k2p2p** [comment]
has this problem after this version

Liu Mingan ***@***.***> 于 2023年4月20日周四 21:08写道：

**Comment by aparcar** [comment]
What is version 537? I'm thinking of something like 22.03.4?

**Comment by 1715173329** [comment]
Ref https://github.com/openwrt/packages/pull/2083

**Comment by 1715173329** [comment]
The bug has been fixed, and ruby will be available again soon. I guess this issue can be closed.
