### ISSUE TITLE
Attended Sysupgrade failed - Mikrotik rb-760igs-create .bin

### ISSUE THREAD

**Issue by Geraldo-GMJ** [openwrt/asu#535]
Good morning everyone, requesting the compilation of my package image.

{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r23228-cd17d8df2a",
    "advanced_mode": "1",
    "sha256_unsigned": "",
    "branch": "23.05",
    "efi": null,
    "profile": "mikrotik,routerboard-760igs",
    "target": "ramips/mt7621",
    "version": "23.05.0-rc2",
    "packages": [
        "adblock",
        "arp-scan",
        "arptables-nft",
        "base-files",
        "block-mount",
        "busybox",
        "ca-bundle",
        "ca-certificates",
        "cgi-io",
        "curl",
        "dnsmasq",
        "drill",
        "dropbear",
        "firewall4",
        "fstools",
        "fwtool",
        "getrandom",
        "htop",
        "iptables-nft",
        "iwinfo",
        "jansson",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-crypto-crc32c",
        "kmod-crypto-hash",
        "kmod-fs-ext4",
        "kmod-gpio-button-hotplug",
        "kmod-ipt-core",
        "kmod-leds-gpio",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc32c",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-log",
        "kmod-nf-log6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nfnetlink",
        "kmod-nft-arp",
        "kmod-nft-core",
        "kmod-nft-fib",
        "kmod-nft-nat",
        "kmod-nft-netdev",
        "kmod-nft-offload",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-sdhci-mt7620",
        "kmod-sfp",
        "kmod-slhc",
        "kmod-usb-storage",
        "kmod-usb-storage-extras",
        "kmod-usb-storage-uas",
        "kmod-usb3",
        "libblobmsg-json",
        "libc",
        "libcurl",
        "libiwinfo",
        "libiwinfo-data",
        "libiwinfo-lua",
        "libjson-c",
        "libjson-script",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "libmnl",
        "libnftnl",
        "libnl-tiny",
        "libopenssl",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuclient",
        "libucode",
        "libustream-mbedtls",
        "libwolfssl",
        "logd",
        "lua",
        "luci",
        "luci-app-attendedsysupgrade",
        "luci-app-firewall",
        "luci-app-opkg",
        "luci-base",
        "luci-compat",
        "luci-i18n-adblock-pt-br",
        "luci-i18n-attendedsysupgrade-pt-br",
        "luci-i18n-base-pt-br",
        "luci-i18n-commands-pt-br",
        "luci-i18n-ddns-pt-br",
        "luci-i18n-firewall-pt-br",
        "luci-i18n-opkg-pt-br",
        "luci-i18n-uhttpd-pt-br",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-mod-admin-full",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-proto-ipv6",
        "luci-proto-ppp",
        "luci-theme-bootstrap",
        "mtd",
        "netifd",
        "nftables-json",
        "ntfs-3g",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openwrt-keyring",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "px5g-wolfssl",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-iwinfo",
        "rpcd-mod-luci",
        "rpcd-mod-rrdns",
        "stubby",
        "tcpdump-mini",
        "ubi-utils",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "ucode",
        "ucode-mod-fs",
        "ucode-mod-ubus",
        "ucode-mod-uci",
        "uhttpd",
        "uhttpd-mod-ubus",
        "urandom-seed",
        "urngd",
        "usbutils",
        "usign",
        "wget-ssl"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-23.132.65998-fa9fb2f"
}

**Comment by danpawlik** [comment]
Should be fine now. Could you close issue?

**Comment by Geraldo-GMJ** [comment]
Obrigado pela ajuda, está funcionando 100% agora.
Thanks for the help, it's working 100% now.

**Comment by Geraldo-GMJ** [comment]
Thanks for the help, it's working 100% now.

 

 

De: Daniel Pawlik ***@***.*** 
Enviada em: domingo, 9 de julho de 2023 07:37
Para: openwrt/asu
Cc: Geraldo-GMJ; Author
Assunto: Re: [openwrt/asu] Attended Sysupgrade failed - Mikrotik rb-760igs-create .bin (Issue #535)

 

Should be fine now. Could you close issue?
