### ISSUE TITLE
Can't install luci-ssl-nginx due to missing uwsgi

### ISSUE THREAD

**Issue by SopaDeMacaco-UmaDelicia** [openwrt/asu#613]
Can't make either attended sysupgrade or build a fresh firmware on firmware-selector, logs tell me there are missing dependencies for luci-ssl-nginx: uwsgi and uwsgi-luci-support. The same configuration works just fine on currently installed 23.05-rc3 on ramips/mt7621/Xiaomi Mi Router 3 Pro and ipq40xx/generic/ASUS RT-AC58U
https://pastebin.com/LkEMWGw8
@Ansuel

**Comment by Ansuel** [comment]
The packages correctly got rebuilt and are not present in faillogs so it's only a matter of waiting.
