### ISSUE TITLE
How to add additional packages using the API

### ISSUE THREAD

**Issue by mcassaniti** [openwrt/asu#626]
When I take a look at the API documentation it suggests I can simply add more packages to the default build by specifying them in the JSON body under `packages` as shown below. This doesn't seem to work and after checking over the code in `asu/build.py` I can't see the packages getting added unless the `diff_packages` option is true.

```JSON
{
    "packages" : ["bmon","tc-full"],
    "target"   : "bcm27xx/bcm2711",
    "profile"  : "rpi-4",
    "version"  : "22.03.5"
}
```

Can someone verify that this is actually the case and perhaps I can get a PR together.

**Comment by aparcar** [comment]
Yea awkward, I should add a test case for this...
