### ISSUE TITLE
Error building the firmware image for Netgear Nighthawk X4S R7800

### ISSUE THREAD

**Issue by luhujp** [openwrt/asu#636]
{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r24163-3e1ac00ccb",
    "advanced_mode": "0",
    "sha256_unsigned": "dd88630b061ccdaa7b8542fee3504e47900a392cb82f9b611dd675781851f191",
    "branch": "SNAPSHOT",
    "efi": null,
    "profile": "netgear,r7800",
    "target": "ipq806x/generic",
    "version": "SNAPSHOT",
    "packages": [
        "0",
        "1",
        "10",
        "100",
        "101",
        "102",
        "103",
        "104",
        "105",
        "106",
        "107",
        "108",
        "109",
        "11",
        "110",
        "111",
        "112",
        "113",
        "114",
        "115",
        "116",
        "117",
        "118",
        "119",
        "12",
        "120",
        "121",
        "122",
        "123",
        "124",
        "125",
        "126",
        "127",
        "128",
        "129",
        "13",
        "130",
        "131",
        "132",
        "133",
        "134",
        "135",
        "136",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "2",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "3",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "4",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "5",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "6",
        "60",
        "61",
        "62",
        "63",
        "64",
        "65",
        "66",
        "67",
        "68",
        "69",
        "7",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "8",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "9",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
        "97",
        "98",
        "99"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-23.292.39411-021c439"
}
STDERR:
Generate local signing keys...
Generate local certificate...
Package list missing or not up-to-date, generating it.

Building package index...
Downloading https://downloads.openwrt.org/snapshots/targets/ipq806x/generic/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/targets/ipq806x/generic/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/base/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/targets/ipq806x/generic/kmods/6.1.59-1-d0c35cc3961048b27873a18cf892ca1b/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_kmods
Downloading https://downloads.openwrt.org/snapshots/targets/ipq806x/generic/kmods/6.1.59-1-d0c35cc3961048b27873a18cf892ca1b/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/luci/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/routing/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/telephony/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/telephony/Packages.sig
Signature check passed.
Downloading file:packages/Packages
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check passed.
Collected errors:
 * opkg_install_cmd: Cannot install package 0.
 * opkg_install_cmd: Cannot install package 1.
 * opkg_install_cmd: Cannot install package 10.
 * opkg_install_cmd: Cannot install package 100.
 * opkg_install_cmd: Cannot install package 101.
 * opkg_install_cmd: Cannot install package 102.
 * opkg_install_cmd: Cannot install package 103.
 * opkg_install_cmd: Cannot install package 104.
 * opkg_install_cmd: Cannot install package 105.
 * opkg_install_cmd: Cannot install package 106.
 * opkg_install_cmd: Cannot install package 107.
 * opkg_install_cmd: Cannot install package 108.
 * opkg_install_cmd: Cannot install package 109.
 * opkg_install_cmd: Cannot install package 11.
 * opkg_install_cmd: Cannot install package 110.
 * opkg_install_cmd: Cannot install package 111.
 * opkg_install_cmd: Cannot install package 112.
 * opkg_install_cmd: Cannot install package 113.
 * opkg_install_cmd: Cannot install package 114.
 * opkg_install_cmd: Cannot install package 115.
 * opkg_install_cmd: Cannot install package 116.
 * opkg_install_cmd: Cannot install package 117.
 * opkg_install_cmd: Cannot install package 118.
 * opkg_install_cmd: Cannot install package 119.
 * opkg_install_cmd: Cannot install package 12.
 * opkg_install_cmd: Cannot install package 120.
 * opkg_install_cmd: Cannot install package 121.
 * opkg_install_cmd: Cannot install package 122.
 * opkg_install_cmd: Cannot install package 123.
 * opkg_install_cmd: Cannot install package 124.
 * opkg_install_cmd: Cannot install package 125.
 * opkg_install_cmd: Cannot install package 126.
 * opkg_install_cmd: Cannot install package 127.
 * opkg_install_cmd: Cannot install package 128.
 * opkg_install_cmd: Cannot install package 129.
 * opkg_install_cmd: Cannot install package 13.
 * opkg_install_cmd: Cannot install package 130.
 * opkg_install_cmd: Cannot install package 131.
 * opkg_install_cmd: Cannot install package 132.
 * opkg_install_cmd: Cannot install package 133.
 * opkg_install_cmd: Cannot install package 134.
 * opkg_install_cmd: Cannot install package 135.
 * opkg_install_cmd: Cannot install package 136.
 * opkg_install_cmd: Cannot install package 14.
 * opkg_install_cmd: Cannot install package 15.
 * opkg_install_cmd: Cannot install package 16.
 * opkg_install_cmd: Cannot install package 17.
 * opkg_install_cmd: Cannot install package 18.
 * opkg_install_cmd: Cannot install package 19.
 * opkg_install_cmd: Cannot install package 2.
 * opkg_install_cmd: Cannot install package 20.
 * opkg_install_cmd: Cannot install package 21.
 * opkg_install_cmd: Cannot install package 22.
 * opkg_install_cmd: Cannot install package 23.
 * opkg_install_cmd: Cannot install package 24.
 * opkg_install_cmd: Cannot install package 25.
 * opkg_install_cmd: Cannot install package 26.
 * opkg_install_cmd: Cannot install package 27.
 * opkg_install_cmd: Cannot install package 28.
 * opkg_install_cmd: Cannot install package 29.
 * opkg_install_cmd: Cannot install package 3.
 * opkg_install_cmd: Cannot install package 30.
 * opkg_install_cmd: Cannot install package 31.
 * opkg_install_cmd: Cannot install package 32.
 * opkg_install_cmd: Cannot install package 33.
 * opkg_install_cmd: Cannot install package 34.
 * opkg_install_cmd: Cannot install package 35.
 * opkg_install_cmd: Cannot install package 36.
 * opkg_install_cmd: Cannot install package 37.
 * opkg_install_cmd: Cannot install package 38.
 * opkg_install_cmd: Cannot install package 39.
 * opkg_install_cmd: Cannot install package 4.
 * opkg_install_cmd: Cannot install package 40.
 * opkg_install_cmd: Cannot install package 41.
 * opkg_install_cmd: Cannot install package 42.
 * opkg_install_cmd: Cannot install package 43.
 * opkg_install_cmd: Cannot install package 44.
 * opkg_install_cmd: Cannot install package 45.
 * opkg_install_cmd: Cannot install package 46.
 * opkg_install_cmd: Cannot install package 47.
 * opkg_install_cmd: Cannot install package 48.
 * opkg_install_cmd: Cannot install package 49.
 * opkg_install_cmd: Cannot install package 5.
 * opkg_install_cmd: Cannot install package 50.
 * opkg_install_cmd: Cannot install package 51.
 * opkg_install_cmd: Cannot install package 52.
 * opkg_install_cmd: Cannot install package 53.
 * opkg_install_cmd: Cannot install package 54.
 * opkg_install_cmd: Cannot install package 55.
 * opkg_install_cmd: Cannot install package 56.
 * opkg_install_cmd: Cannot install package 57.
 * opkg_install_cmd: Cannot install package 58.
 * opkg_install_cmd: Cannot install package 59.
 * opkg_install_cmd: Cannot install package 6.
 * opkg_install_cmd: Cannot install package 60.
 * opkg_install_cmd: Cannot install package 61.
 * opkg_install_cmd: Cannot install package 62.
 * opkg_install_cmd: Cannot install package 63.
 * opkg_install_cmd: Cannot install package 64.
 * opkg_install_cmd: Cannot install package 65.
 * opkg_install_cmd: Cannot install package 66.
 * opkg_install_cmd: Cannot install package 67.
 * opkg_install_cmd: Cannot install package 68.
 * opkg_install_cmd: Cannot install package 69.
 * opkg_install_cmd: Cannot install package 7.
 * opkg_install_cmd: Cannot install package 70.
 * opkg_install_cmd: Cannot install package 71.
 * opkg_install_cmd: Cannot install package 72.
 * opkg_install_cmd: Cannot install package 73.
 * opkg_install_cmd: Cannot install package 74.
 * opkg_install_cmd: Cannot install package 75.
 * opkg_install_cmd: Cannot install package 76.
 * opkg_install_cmd: Cannot install package 77.
 * opkg_install_cmd: Cannot install package 78.
 * opkg_install_cmd: Cannot install package 79.
 * opkg_install_cmd: Cannot install package 8.
 * opkg_install_cmd: Cannot install package 80.
 * opkg_install_cmd: Cannot install package 81.
 * opkg_install_cmd: Cannot install package 82.
 * opkg_install_cmd: Cannot install package 83.
 * opkg_install_cmd: Cannot install package 84.
 * opkg_install_cmd: Cannot install package 85.
 * opkg_install_cmd: Cannot install package 86.
 * opkg_install_cmd: Cannot install package 87.
 * opkg_install_cmd: Cannot install package 88.
 * opkg_install_cmd: Cannot install package 89.
 * opkg_install_cmd: Cannot install package 9.
 * opkg_install_cmd: Cannot install package 90.
 * opkg_install_cmd: Cannot install package 91.
 * opkg_install_cmd: Cannot install package 92.
 * opkg_install_cmd: Cannot install package 93.
 * opkg_install_cmd: Cannot install package 94.
 * opkg_install_cmd: Cannot install package 95.
 * opkg_install_cmd: Cannot install package 96.
 * opkg_install_cmd: Cannot install package 97.
 * opkg_install_cmd: Cannot install package 98.
 * opkg_install_cmd: Cannot install package 99.
make[2]: *** [Makefile:189: package_install] Error 255
make[1]: *** [Makefile:154: _call_manifest] Error 2
make: *** [Makefile:274: manifest] Error 2

**Comment by h-arnold** [comment]
I had the same issue trying to upgrade from 22.03.5 to 23.05.0. The error message I got was:

`{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r20134-5f15225c1e",
    "advanced_mode": "1",
    "branch": "22.03",
    "efi": null,
    "profile": "netgear,r7800",
    "target": "ipq806x/generic",
    "version": "23.05.0",
    "packages": [
        "ath10k-firmware-qca9984-ct",
        "base-files",
        "busybox",
        "ca-bundle",
        "cgi-io",
        "collectd-mod-thermal",
        "dnsmasq",
        "dropbear",
        "firewall4",
        "fstools",
        "fwtool",
        "getrandom",
        "hostapd-common",
        "iw",
        "iwinfo",
        "jansson",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-ata-ahci",
        "kmod-ata-ahci-platform",
        "kmod-ata-core",
        "kmod-ath",
        "kmod-ath10k-ct",
        "kmod-cfg80211",
        "kmod-crypto-aead",
        "kmod-crypto-ccm",
        "kmod-crypto-cmac",
        "kmod-crypto-crc32c",
        "kmod-crypto-ctr",
        "kmod-crypto-gcm",
        "kmod-crypto-gf128",
        "kmod-crypto-ghash",
        "kmod-crypto-hash",
        "kmod-crypto-hmac",
        "kmod-crypto-manager",
        "kmod-crypto-null",
        "kmod-crypto-rng",
        "kmod-crypto-seqiv",
        "kmod-crypto-sha256",
        "kmod-gpio-button-hotplug",
        "kmod-hwmon-core",
        "kmod-leds-gpio",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc32c",
        "kmod-mac80211",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-log",
        "kmod-nf-log6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nfnetlink",
        "kmod-nft-core",
        "kmod-nft-fib",
        "kmod-nft-nat",
        "kmod-nft-offload",
        "kmod-nls-base",
        "kmod-phy-qcom-ipq806x-usb",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-ramoops",
        "kmod-scsi-core",
        "kmod-slhc",
        "kmod-usb-core",
        "kmod-usb-dwc3",
        "kmod-usb-dwc3-qcom",
        "kmod-usb-ehci",
        "kmod-usb-ledtrig-usbport",
        "kmod-usb-ohci",
        "kmod-usb-xhci-hcd",
        "kmod-usb2",
        "kmod-usb3",
        "libblobmsg-json",
        "libiwinfo",
        "libiwinfo-data",
        "libiwinfo-lua",
        "libjson-c",
        "libjson-script",
        "liblua",
        "liblucihttp",
        "liblucihttp-lua",
        "libmnl",
        "libnftnl",
        "libnl-tiny",
        "libubox",
        "libubus",
        "libubus-lua",
        "libuci",
        "libuclient",
        "libucode",
        "libustream-wolfssl",
        "libwolfssl",
        "logd",
        "lua",
        "luci",
        "luci-app-attendedsysupgrade",
        "luci-app-firewall",
        "luci-app-opkg",
        "luci-app-statistics",
        "luci-base",
        "luci-i18n-attendedsysupgrade-en",
        "luci-i18n-statistics-en",
        "luci-lib-base",
        "luci-lib-ip",
        "luci-lib-jsonc",
        "luci-lib-nixio",
        "luci-mod-admin-full",
        "luci-mod-network",
        "luci-mod-status",
        "luci-mod-system",
        "luci-proto-ipv6",
        "luci-proto-ppp",
        "luci-ssl",
        "luci-theme-bootstrap",
        "mtd",
        "netifd",
        "nftables-json",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openwrt-keyring",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "px5g-wolfssl",
        "rpcd",
        "rpcd-mod-file",
        "rpcd-mod-iwinfo",
        "rpcd-mod-luci",
        "rpcd-mod-rrdns",
        "swconfig",
        "ubi-utils",
        "uboot-envtools",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "ucode",
        "ucode-mod-fs",
        "ucode-mod-ubus",
        "ucode-mod-uci",
        "uhttpd",
        "uhttpd-mod-ubus",
        "urandom-seed",
        "urngd",
        "usign",
        "wireless-regdb",
        "wpad-basic-wolfssl"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-23.093.42303-58b861d"
}

STDERR:

Generate local signing keys...
Generate local certificate...
Package list missing or not up-to-date, generating it.

Building package index...
Downloading https://downloads.openwrt.org/releases/23.05.0/targets/ipq806x/generic/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_core
Downloading https://downloads.openwrt.org/releases/23.05.0/targets/ipq806x/generic/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/base/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_base
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/luci/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_luci
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_packages
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/routing/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_routing
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/telephony/Packages.gz
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/arm_cortex-a15_neon-vfpv4/telephony/Packages.sig
Signature check passed.
Downloading file:packages/Packages
Updated list of available packages in /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/../../../../builder/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check passed.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-i18n-attendedsysupgrade-en.
 * opkg_install_cmd: Cannot install package luci-i18n-statistics-en.
 * check_data_file_clashes: Package libustream-mbedtls20201210 wants to install file /builder/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/lib/libustream-ssl.so
	But that file is already provided by package  * libustream-wolfssl20201210
 * opkg_install_cmd: Cannot install package luci-ssl.
make[2]: *** [Makefile:189: package_install] Error 255
make[1]: *** [Makefile:154: _call_manifest] Error 2
make: *** [Makefile:274: manifest] Error 2
`
