### ISSUE TITLE
Error building the firmware image on qualcommax/ipq807

### ISSUE THREAD

**Issue by robert-pajak** [openwrt/asu#671]
Could this issue be investigated please?
I am trying to upgrade using Luci Attended Sysupgrade but I'm getting the following error

Error building the firmware image
Server response: Error: Impossible package selection

[Please report the error message and request](https://github.com/openwrt/asu/issues)
Request Data:

```
{
    "url": "https://sysupgrade.openwrt.org",
    "revision": "r24450-944d3526a3",
    "advanced_mode": "1",
    "sha256_unsigned": "",
    "branch": "SNAPSHOT",
    "efi": null,
    "request_hash": "739fa5fe7c5ff119899efd7a42cffbc5",
    "profile": "xiaomi,ax9000",
    "target": "qualcommax/ipq807x",
    "version": "SNAPSHOT",
    "packages": [
        "ath10k-firmware-qca9887-ct-full-htt",
        "ath11k-firmware-ipq8074",
        "ath11k-firmware-qcn9074",
        "auc",
        "base-files",
        "busybox",
        "ca-bundle",
        "collectd-mod-contextswitch",
        "collectd-mod-cpufreq",
        "collectd-mod-curl",
        "collectd-mod-dhcpleases",
        "collectd-mod-entropy",
        "collectd-mod-filecount",
        "collectd-mod-fscache",
        "collectd-mod-irq",
        "collectd-mod-modbus",
        "collectd-mod-mqtt",
        "collectd-mod-ntpd",
        "collectd-mod-openvpn",
        "collectd-mod-ping",
        "collectd-mod-processes",
        "collectd-mod-tcpconns",
        "ddns-scripts-route53",
        "dnsmasq",
        "dropbear",
        "e2fsprogs",
        "ethtool",
        "firewall4",
        "fstools",
        "fwtool",
        "getrandom",
        "hostapd-common",
        "htop",
        "inotifywait",
        "inotifywatch",
        "iperf3",
        "ipq-wifi-xiaomi_ax9000",
        "iptraf-ng",
        "iw",
        "iwinfo",
        "jansson",
        "jshn",
        "jsonfilter",
        "kernel",
        "kmod-ath",
        "kmod-ath10k-ct",
        "kmod-ath11k",
        "kmod-ath11k-ahb",
        "kmod-ath11k-pci",
        "kmod-cfg80211",
        "kmod-crypto-acompress",
        "kmod-crypto-aead",
        "kmod-crypto-ccm",
        "kmod-crypto-cmac",
        "kmod-crypto-crc32c",
        "kmod-crypto-ctr",
        "kmod-crypto-gcm",
        "kmod-crypto-gf128",
        "kmod-crypto-ghash",
        "kmod-crypto-hash",
        "kmod-crypto-hmac",
        "kmod-crypto-manager",
        "kmod-crypto-michael-mic",
        "kmod-crypto-null",
        "kmod-crypto-rng",
        "kmod-crypto-seqiv",
        "kmod-crypto-sha512",
        "kmod-fs-ext4",
        "kmod-gpio-button-hotplug",
        "kmod-hwmon-core",
        "kmod-leds-gpio",
        "kmod-lib-crc-ccitt",
        "kmod-lib-crc16",
        "kmod-lib-crc32c",
        "kmod-lib-lzo",
        "kmod-libphy",
        "kmod-mac80211",
        "kmod-nf-conntrack",
        "kmod-nf-conntrack6",
        "kmod-nf-flow",
        "kmod-nf-log",
        "kmod-nf-log6",
        "kmod-nf-nat",
        "kmod-nf-reject",
        "kmod-nf-reject6",
        "kmod-nfnetlink",
        "kmod-nft-core",
        "kmod-nft-fib",
        "kmod-nft-nat",
        "kmod-nft-offload",
        "kmod-nls-base",
        "kmod-ovpn-dco-v2",
        "kmod-phy-aquantia",
        "kmod-ppp",
        "kmod-pppoe",
        "kmod-pppox",
        "kmod-qca-nss-dp",
        "kmod-qca-ssdk",
        "kmod-qrtr",
        "kmod-qrtr-smd",
        "kmod-slhc",
        "kmod-thermal",
        "kmod-tun",
        "kmod-usb-core",
        "kmod-usb-dwc3",
        "kmod-usb-dwc3-qcom",
        "kmod-usb-xhci-hcd",
        "kmod-usb3",
        "libblkid",
        "libblobmsg-json",
        "libc",
        "libcomerr",
        "libext2fs",
        "libffmpeg-mini",
        "libiwinfo",
        "libiwinfo-data",
        "libjson-c",
        "libjson-script",
        "libmbedtls",
        "libmnl",
        "libmosquitto-ssl",
        "libnftnl",
        "libnl-tiny",
        "libsmartcols",
        "libss",
        "libubox",
        "libubus",
        "libuci",
        "libuclient",
        "libucode",
        "libuhttpd-mbedtls",
        "libustream-mbedtls",
        "libuuid",
        "logd",
        "losetup",
        "luci",
        "luci-app-adblock",
        "luci-app-attendedsysupgrade",
        "luci-app-commands",
        "luci-app-ddns",
        "luci-app-ksmbd",
        "luci-app-minidlna",
        "luci-app-openvpn",
        "luci-app-statistics",
        "luci-app-wol",
        "luci-proto-wireguard",
        "luci-ssl",
        "minidlna",
        "mtd",
        "nano",
        "netifd",
        "nftables-json",
        "odhcp6c",
        "odhcpd-ipv6only",
        "openvpn-mbedtls",
        "openwrt-keyring",
        "opkg",
        "ppp",
        "ppp-mod-pppoe",
        "procd",
        "procd-seccomp",
        "procd-ujail",
        "qrencode",
        "shadow-groupadd",
        "shadow-groups",
        "shadow-passwd",
        "ubi-utils",
        "uboot-envtools",
        "ubox",
        "ubus",
        "ubusd",
        "uci",
        "uclient-fetch",
        "ucode",
        "ucode-mod-fs",
        "ucode-mod-nl80211",
        "ucode-mod-rtnl",
        "ucode-mod-ubus",
        "ucode-mod-uci",
        "ucode-mod-uloop",
        "urandom-seed",
        "urngd",
        "usign",
        "usteer",
        "wireless-regdb",
        "wpad-basic-mbedtls"
    ],
    "diff_packages": true,
    "filesystem": "squashfs",
    "client": "luci/git-23.292.39411-021c439"
}
```
STDERR:
```
Generate local signing keys...
Generate local certificate...
Package list missing or not up-to-date, generating it.

Building package index...
Downloading https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/kmods/6.1.64-1-1763aacc7248702f887609f8c80e68c4/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_kmods
Downloading https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/kmods/6.1.64-1-1763aacc7248702f887609f8c80e68c4/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/Packages.sig
Signature check passed.
Downloading file:packages/Packages
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check passed.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20231130 for mtd
 * pkg_hash_fetch_best_installation_candidate: Packages for mtd found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package mtd.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for mtd:
 * 	libubox20231130
 * opkg_install_cmd: Cannot install package mtd.
make[2]: *** [Makefile:189: package_install] Error 255
make[1]: *** [Makefile:154: _call_manifest] Error 2
make: *** [Makefile:274: manifest] Error 2
```
command line `auc` doesn't work either due to the same (or similar) issue 
`# auc
auc/0.3.2-1
Server:    https://sysupgrade.openwrt.org
Running:   SNAPSHOT r24450-944d3526a3 on qualcommax/ipq807x (xiaomi,ax9000)
Available: SNAPSHOT r24550-f909059b74
Requesting package lists...
 kmod-crypto-gf128: 6.1.62-1 -> 6.1.64-1
 kmod-usb-core: 6.1.62-1 -> 6.1.64-1
 ubus: 2023-11-14-b3e8c4ef-1 -> 2023-11-28-f84eb599-1
 kmod-crypto-manager: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-ctr: 6.1.62-1 -> 6.1.64-1
 ddns-scripts-services: 2.8.2-41 -> 2.8.2-42
 kmod-nft-fib: 6.1.62-1 -> 6.1.64-1
 kmod-nfnetlink: 6.1.62-1 -> 6.1.64-1
 kmod-ath11k: 6.1.62+6.5-1 -> 6.1.64+6.5-1
 libubus-lua: 2023-11-14-b3e8c4ef-1 -> 2023-11-28-f84eb599-1
 kmod-crypto-hash: 6.1.62-1 -> 6.1.64-1
 kmod-nf-reject6: 6.1.62-1 -> 6.1.64-1
 kmod-tun: 6.1.62-1 -> 6.1.64-1
 kmod-fs-ksmbd: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-aead: 6.1.62-1 -> 6.1.64-1
 kmod-usb-dwc3: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-md4: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-md5: 6.1.62-1 -> 6.1.64-1
 kmod-nf-flow: 6.1.62-1 -> 6.1.64-1
 kmod-lib-crc-ccitt: 6.1.62-1 -> 6.1.64-1
 kmod-phy-aquantia: 6.1.62-1 -> 6.1.64-1
 kmod-asn1-decoder: 6.1.62-1 -> 6.1.64-1
 kmod-pppoe: 6.1.62-1 -> 6.1.64-1
 libubus: 2023-11-14-b3e8c4ef-1 -> 2023-11-28-f84eb599-1
 kmod-pppox: 6.1.62-1 -> 6.1.64-1
 kmod-nf-reject: 6.1.62-1 -> 6.1.64-1
 base-files: 1549-r24450-944d3526a3 -> 1549-r24550-f909059b74
 kmod-lib-crc16: 6.1.62-1 -> 6.1.64-1
 kmod-nf-nat: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-crc32c: 6.1.62-1 -> 6.1.64-1
 libustream-mbedtls: 2023-02-25-498f6e26-1 -> 2023-11-26-263b9a97-1
 kmod-usb-dwc3-qcom: 6.1.62-1 -> 6.1.64-1
 ddns-scripts: 2.8.2-41 -> 2.8.2-42
 kmod-usb-xhci-hcd: 6.1.62-1 -> 6.1.64-1
 kmod-oid-registry: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-hmac: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-sha256: 6.1.62-1 -> 6.1.64-1
 ubusd: 2023-11-14-b3e8c4ef-1 -> 2023-11-28-f84eb599-1
 kmod-crypto-acompress: 6.1.62-1 -> 6.1.64-1
 kmod-lib-crc32c: 6.1.62-1 -> 6.1.64-1
 kmod-qca-ssdk: 6.1.62+2023-10-04-23a5aa4a-4 -> 6.1.64+2023-10-04-23a5aa4a-4
 kmod-crypto-sha512: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-seqiv: 6.1.62-1 -> 6.1.64-1
 kmod-nft-nat: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-lib-chacha20poly1305: 6.1.62-1 -> 6.1.64-1
 kmod-usb3: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-lib-poly1305: 6.1.62-1 -> 6.1.64-1
 kmod-thermal: 6.1.62-1 -> 6.1.64-1
 kmod-ovpn-dco-v2: 6.1.62+0.2.20230426-1 -> 6.1.64+0.2.20230426-1
 kmod-udptunnel4: 6.1.62-1 -> 6.1.64-1
 kmod-udptunnel6: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-ghash: 6.1.62-1 -> 6.1.64-1
 kmod-fs-ext4: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-kpp: 6.1.62-1 -> 6.1.64-1
 kmod-hwmon-core: 6.1.62-1 -> 6.1.64-1
 kmod-nls-utf8: 6.1.62-1 -> 6.1.64-1
 kmod-qrtr-smd: 6.1.62-1 -> 6.1.64-1
 libjson-script: 2023-05-23-75a3b870-1 -> 2023-11-28-e80dc00e-1
 kmod-fs-smbfs-common: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-ccm: 6.1.62-1 -> 6.1.64-1
 kmod-nf-log: 6.1.62-1 -> 6.1.64-1
 kmod-leds-gpio: 6.1.62-1 -> 6.1.64-1
 kmod-gpio-button-hotplug: 6.1.62-3 -> 6.1.64-3
 kmod-qrtr: 6.1.62-1 -> 6.1.64-1
 kmod-nf-log6: 6.1.62-1 -> 6.1.64-1
 kmod-wireguard: 6.1.62-1 -> 6.1.64-1
 kmod-mac80211: 6.1.62+6.5-1 -> 6.1.64+6.5-1
 kmod-qca-nss-dp: 6.1.62+2023-06-06-fa674644-2 -> 6.1.64+2023-06-06-fa674644-2
 kmod-crypto-michael-mic: 6.1.62-1 -> 6.1.64-1
 kmod-ath11k-pci: 6.1.62+6.5-1 -> 6.1.64+6.5-1
 kmod-crypto-ecb: 6.1.62-1 -> 6.1.64-1
 kmod-libphy: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-des: 6.1.62-1 -> 6.1.64-1
 jshn: 2023-05-23-75a3b870-1 -> 2023-11-28-e80dc00e-1
 kmod-nft-offload: 6.1.62-1 -> 6.1.64-1
 kmod-ppp: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-null: 6.1.62-1 -> 6.1.64-1
 ddns-scripts-route53: 2.8.2-41 -> 2.8.2-42
 kmod-nf-conntrack: 6.1.62-1 -> 6.1.64-1
 libblobmsg-json: 2023-05-23-75a3b870-1 -> 2023-11-28-e80dc00e-1
 kmod-crypto-gcm: 6.1.62-1 -> 6.1.64-1
 kmod-ath10k-ct: 6.1.62+2023-06-05-fadd0768-1 -> 6.1.64+2023-06-05-fadd0768-1
 kmod-crypto-cmac: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-rng: 6.1.62-1 -> 6.1.64-1
 kmod-nf-conntrack6: 6.1.62-1 -> 6.1.64-1
 kmod-ath11k-ahb: 6.1.62+6.5-1 -> 6.1.64+6.5-1
 kmod-lib-lzo: 6.1.62-1 -> 6.1.64-1
 kmod-ath: 6.1.62+6.5-1 -> 6.1.64+6.5-1
 kmod-crypto-lib-curve25519: 6.1.62-1 -> 6.1.64-1
 kmod-crypto-lib-chacha20: 6.1.62-1 -> 6.1.64-1
 luci-mod-network: git-23.323.00633-a9849ed -> git-23.326.49267-ef315b0
 kmod-nft-core: 6.1.62-1 -> 6.1.64-1
 kmod-nls-base: 6.1.62-1 -> 6.1.64-1
 libubox: 2023-05-23-75a3b870-1 -> 2023-11-28-e80dc00e-1
 kmod-qrtr-mhi: 6.1.62-1 -> 6.1.64-1
 libudebug: 2023-11-20-759d9404 -> 2023-11-27-d4b99820
 kmod-slhc: 6.1.62-1 -> 6.1.64-1
 kmod-cfg80211: 6.1.62+6.5-1 -> 6.1.64+6.5-1
 kmod-mhi-bus: 6.1.62-1 -> 6.1.64-1
Are you sure you want to continue the upgrade process? [N/y] y
Requesting build..........................................................Generate local signing keys...
Generate local certificate...
Package list missing or not up-to-date, generating it.

Building package index...
Downloading https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/kmods/6.1.64-1-1763aacc7248702f887609f8c80e68c4/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_kmods
Downloading https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/kmods/6.1.64-1-1763aacc7248702f887609f8c80e68c4/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/Packages.gz
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/Packages.sig
Signature check passed.
Downloading file:packages/Packages
Updated list of available packages in /builder/build_dir/target-aarch64_cortex-a53_musl/root-qualcommax/../../../../builder/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check passed.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20231130 for mtd
 * pkg_hash_fetch_best_installation_candidate: Packages for mtd found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package mtd.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for mtd:
 *      libubox20231130
 * opkg_install_cmd: Cannot install package mtd.
make[2]: *** [Makefile:189: package_install] Error 255
make[1]: *** [Makefile:154: _call_manifest] Error 2
make: *** [Makefile:274: manifest] Error 2
Error: Impossible package selection
Bad message (74)
`

**Comment by rennewpeter** [comment]
I have the same error

**Comment by robert-pajak** [comment]
Issue is now resolved
