### ISSUE TITLE
Unable to reach sysupgrade server 

### ISSUE THREAD

**Issue by Crav88** [openwrt/asu#697]
Hi there ,

just for let you know that from router I’m unable to reach the api at : https://sysupgrade.openwrt.org

no rush still holiday time . But only for your information! 

Stay safe 
Best regards 

Crav

**Comment by lars18th** [comment]
Hi,

Yes, it seems that the server goes off for a lot times recently. As a constructive opinion, I'll suggest to add some STATUS page with a list of open servers. Then the user could check/search for alternatives. What you think?

Regards.

**Comment by Crav88** [comment]
It’s working now ! Thanks a lot
