### ISSUE TITLE
Revert "Allow custom UCI defaults: False"

### ISSUE THREAD

**Issue by hashcan** [openwrt/asu#711]
Hello world, 
I would like to request to revert the commit that changed the "Allow custom UCI defaults" option from True to False for the https://sysupgrade.openwrt.org website. This option allows us to use a custom uci-default script to configure the image after flashing. This is very useful for setting up things like network, firewall, wireless, and other settings that are specific to our devices and environments.
as I use the "don't keep the current configurations" option to flash the image, I rely on the custom uci-default script to set up the device automatically. Without this option, we have to manually configure the device after flashing, which is tedious and error-prone.

**Comment by Rinat84** [comment]
[ImmortalWrt](https://firmware-selector.immortalwrt.org/) this feature works

**Comment by aparcar** [comment]
I set the according env variable which I forgot in the last deployment, enjoy.

**Comment by AlanFinotty** [comment]
https://github.com/openwrt/asu/blob/main/asu/config.py#L14

**Comment by hashcan** [comment]
@aparcar can you please switch it on again ?

**Comment by hansenjt91** [comment]
How does this keep getting turned off?
