### ISSUE TITLE
Cannot update to new version

### ISSUE THREAD

**Issue by taile007** [openwrt/asu#736]
![Uploading Screenshot (113).png…]()

**Comment by cherinyy** [comment]
https://github.com/openwrt/asu/issues/732#issuecomment-1928547622

**Comment by aparcar** [comment]
Should be working again, Docker containers were updated from an outdated mirror. Please reopen if issue still exists.

**Comment by taile007** [comment]
Thank you openwrt for now updating to a new stable version
Thank you very much

Vào Th 2, 12 thg 2, 2024 vào lúc 23:04 Paul Spooren <
***@***.***> đã viết:
