### ISSUE TITLE
OpenWRT Attended SysUpgrade Fails

### ISSUE THREAD

**Issue by Rachel2jcb** [openwrt/asu#737]
see attached report
[Attended-Sysupgrade-fails.txt](https://github.com/openwrt/asu/files/14196223/Attended-Sysupgrade-fails.txt)

**Comment by aparcar** [comment]
Should be working again, Docker containers were updated from an outdated mirror. Please reopen if issue still exists.

**Comment by Rachel2jcb** [comment]
Thank you.
Unfortunately, the problem persists. 
[AttendedSysupgrade.txt](https://github.com/openwrt/asu/files/14258404/AttendedSysupgrade.txt)
