### ISSUE TITLE
update: 'versions' list contains branch name in overview.json

### ISSUE THREAD

**Issue by efahl** [openwrt/asu#930]
This appeared today.  Look in https://sysupgrade.openwrt.org/json/v1/overview.json and the branches["*"].versions  lists all contain the branch name.  The https://downloads.openwrt.org/.versions.json contents look fine, so maybe it's coming from the settings via `get_branch`???
```
...
  "branches": {
    "21.02": {
      "path": "releases/{version}",
      "enabled": true,
      "path_packages": "DEPRECATED",
      "name": "21.02",
      "versions": [
        "21.02.7",
        "21.02-SNAPSHOT",
        "21.02"             <<<<<========  Should not be here
      ],
...
```

**Comment by aparcar** [comment]
Removed, sorry script issue on my end.

**Comment by efahl** [comment]
👍🏼  I figured it was something like that when the release snapshots appeared at the same time.
